-- 0003_alter_app_user_create_auth_token (generated by lidza gen from schema.lidza)
ALTER TABLE app_user ADD COLUMN verified_at timestamptz;
CREATE TABLE auth_token (
  id text PRIMARY KEY,
  purpose text NOT NULL,
  subject text NOT NULL,
  hash text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX auth_token_purpose_idx ON auth_token (purpose);
CREATE INDEX auth_token_subject_idx ON auth_token (subject);
