-- 0004_create_mail_message (generated by lidza gen from schema.lidza)
CREATE TABLE mail_message (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  recipient text NOT NULL,
  subject text NOT NULL,
  text text,
  html text,
  template text,
  status text NOT NULL,
  provider_id text,
  error text,
  attempts integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  sent_at timestamptz
);
CREATE INDEX mail_message_recipient_idx ON mail_message (recipient);
CREATE INDEX mail_message_status_idx ON mail_message (status);
CREATE INDEX mail_message_created_at_idx ON mail_message (created_at);
