-- 0007_create_auth_account (generated by lidza gen from schema.lidza)
CREATE TABLE auth_account (
  subject text PRIMARY KEY,
  label text,
  disabled_at timestamptz,
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now()
);
