-- 0010_alter_mail_message (generated by lidza gen from schema.lidza)
ALTER TABLE mail_message ADD COLUMN from_address text;
ALTER TABLE mail_message ADD COLUMN reply_to text;
ALTER TABLE mail_message ADD COLUMN headers jsonb;
