-- 0010_alter_mail_message (generated by lidza gen from schema.lidza)
ALTER TABLE mail_message DROP COLUMN headers;
ALTER TABLE mail_message DROP COLUMN reply_to;
ALTER TABLE mail_message DROP COLUMN from_address;
