-- 0011_alter_mail_message (generated by lidza gen from schema.lidza)
ALTER TABLE mail_message ADD COLUMN cc text[];
ALTER TABLE mail_message ADD COLUMN bcc text[];
ALTER TABLE mail_message ADD COLUMN attachments jsonb;
