-- 0011_alter_mail_message (generated by lidza gen from schema.lidza)
ALTER TABLE mail_message DROP COLUMN attachments;
ALTER TABLE mail_message DROP COLUMN bcc;
ALTER TABLE mail_message DROP COLUMN cc;
