-- 0012_create_auth_connection (generated by lidza gen from schema.lidza)
CREATE TABLE auth_connection (
  id text PRIMARY KEY,
  owner text NOT NULL,
  provider text NOT NULL,
  subject text NOT NULL,
  login text NOT NULL DEFAULT '',
  scopes text NOT NULL DEFAULT '',
  token_type text NOT NULL DEFAULT '',
  access_sealed text NOT NULL,
  refresh_sealed text NOT NULL DEFAULT '',
  expires_at timestamptz,
  reconnect boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX auth_connection_owner_provider_key ON auth_connection (owner, provider);
