// Package recipes turns the "Recipes" section of an app's guide
// (docs/lidza-guide.md) into task recipes: prompts served by `lidza mcp`,
// skills for Claude Code (.claude/skills) and Codex (.agents/skills, the
// Agent Skills layout), and Gemini CLI commands (.gemini/commands/lidza).
// The guide is the only source; everything else is rewritten from it by
// `lidza gen`.
package recipes

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// GuideFile is the app guide, relative to the project root.
const GuideFile = "docs/lidza-guide.md"

// SkillsDir is where Claude Code reads skills, relative to the project
// root; AgentsSkillsDir is the Agent Skills layout Codex reads. Both get
// the same SKILL.md files.
const (
	SkillsDir       = ".claude/skills"
	AgentsSkillsDir = ".agents/skills"
	// GeminiCommandsDir holds one TOML per recipe, invoked as
	// /lidza:<name> in Gemini CLI.
	GeminiCommandsDir = ".gemini/commands/lidza"
)

// OutputDirs lists every directory the recipes are written to.
var OutputDirs = []string{SkillsDir, AgentsSkillsDir, GeminiCommandsDir}

// Heading is the guide section that holds the recipes.
const Heading = "## Recipes"

// marker is the first body line of every generated skill; only files
// carrying it are ever removed.
const marker = "<!-- Generated by lidza gen from " + GuideFile + ". Edit the guide, not this file. -->"

// Recipe is one task: a level-3 heading under "## Recipes" and its text.
type Recipe struct {
	// Name is the slug of the title: the prompt name and the skill
	// directory ("add-api-route").
	Name  string `json:"name"`
	Title string `json:"title"`
	// Description is the first paragraph of the body on one line.
	Description string `json:"description"`
	// Body is the markdown under the heading, trimmed.
	Body string `json:"body"`
}

// Parse extracts the recipes from the guide's markdown. A guide without a
// Recipes section yields none.
func Parse(guide string) []Recipe {
	lines := strings.Split(strings.ReplaceAll(guide, "\r\n", "\n"), "\n")
	var out []Recipe
	in := false
	var cur *Recipe
	var body []string
	flush := func() {
		if cur == nil {
			return
		}
		cur.Body = strings.TrimSpace(strings.Join(body, "\n"))
		cur.Description = firstParagraph(cur.Body)
		out = append(out, *cur)
		cur, body = nil, nil
	}
	for _, l := range lines {
		switch {
		case strings.HasPrefix(l, "## "):
			flush()
			in = strings.TrimSpace(l) == Heading
		case in && strings.HasPrefix(l, "### "):
			flush()
			title := strings.TrimSpace(strings.TrimPrefix(l, "### "))
			cur = &Recipe{Name: Slug(title), Title: title}
		case in && cur != nil:
			body = append(body, l)
		}
	}
	flush()
	return out
}

var nonSlug = regexp.MustCompile(`[^a-z0-9]+`)

// Slug lowercases a title, drops articles and joins the words with
// dashes: "Add an API route" is "add-api-route".
func Slug(title string) string {
	var words []string
	for _, w := range strings.Split(nonSlug.ReplaceAllString(strings.ToLower(title), "-"), "-") {
		if w == "" || w == "a" || w == "an" || w == "the" {
			continue
		}
		words = append(words, w)
	}
	return strings.Join(words, "-")
}

func firstParagraph(body string) string {
	para := body
	if i := strings.Index(body, "\n\n"); i >= 0 {
		para = body[:i]
	}
	return strings.Join(strings.Fields(para), " ")
}

// Load reads the guide in dir and parses it.
func Load(dir string) ([]Recipe, error) {
	data, err := os.ReadFile(filepath.Join(dir, GuideFile))
	if err != nil {
		return nil, err
	}
	return Parse(string(data)), nil
}

// Skill renders a recipe as a SKILL.md.
func Skill(r Recipe) string {
	var b strings.Builder
	fmt.Fprintf(&b, "---\nname: %s\ndescription: %s\n---\n%s\n\n# %s\n\n%s\n", r.Name, yamlString(r.Description), marker, r.Title, r.Body)
	return b.String()
}

func yamlString(s string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(s) + `"`
}

// geminiMarker is the first line of every generated Gemini command.
const geminiMarker = "# Generated by lidza gen from " + GuideFile + ". Edit the guide, not this file."

// GeminiCommand renders a recipe as a Gemini CLI custom command: the
// recipe as the prompt, the user's words appended as the task.
func GeminiCommand(r Recipe) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s\ndescription = %s\nprompt = \"\"\"\n# %s\n\n%s\n\nTask: {{args}}\n\"\"\"\n", geminiMarker, tomlString(r.Description), r.Title, strings.ReplaceAll(r.Body, `"""`, `""\"`))
	return b.String()
}

func tomlString(s string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(s) + `"`
}

// WriteSkills writes every recipe as a skill for Claude Code and Codex
// and as a Gemini command, and removes generated files whose recipe is
// gone. It returns the paths it wrote, relative to dir.
func WriteSkills(dir string, rs []Recipe) ([]string, error) {
	var written []string
	for _, skillsDir := range []string{SkillsDir, AgentsSkillsDir} {
		w, err := writeSet(dir, skillsDir, rs, func(r Recipe) (string, string) { return filepath.Join(r.Name, "SKILL.md"), Skill(r) }, marker)
		if err != nil {
			return nil, err
		}
		written = append(written, w...)
	}
	w, err := writeSet(dir, GeminiCommandsDir, rs, func(r Recipe) (string, string) { return r.Name + ".toml", GeminiCommand(r) }, geminiMarker)
	if err != nil {
		return nil, err
	}
	written = append(written, w...)
	sort.Strings(written)
	return written, nil
}

// writeSet writes one file per recipe under dir/sub (path and content
// from render) and removes entries under sub that carry the marker but
// belong to no recipe.
func writeSet(dir, sub string, rs []Recipe, render func(Recipe) (string, string), mark string) ([]string, error) {
	root := filepath.Join(dir, sub)
	keep := map[string]bool{}
	var written []string
	for _, r := range rs {
		if r.Name == "" {
			continue
		}
		rel, content := render(r)
		keep[strings.Split(filepath.ToSlash(rel), "/")[0]] = true
		p := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			return nil, err
		}
		written = append(written, filepath.ToSlash(filepath.Join(sub, rel)))
		if old, err := os.ReadFile(p); err == nil && string(old) == content {
			continue
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			return nil, err
		}
	}
	entries, err := os.ReadDir(root)
	if err != nil {
		return written, nil
	}
	for _, e := range entries {
		if keep[e.Name()] {
			continue
		}
		p := filepath.Join(root, e.Name())
		if e.IsDir() {
			p = filepath.Join(p, "SKILL.md")
		}
		data, err := os.ReadFile(p)
		if err != nil || !strings.Contains(string(data), mark) {
			continue
		}
		if err := os.RemoveAll(filepath.Join(root, e.Name())); err != nil {
			return nil, err
		}
	}
	return written, nil
}

// Sync loads the guide and writes the skills. A project without a guide
// is left alone.
func Sync(dir string) ([]Recipe, error) {
	rs, err := Load(dir)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	_, err = WriteSkills(dir, rs)
	return rs, err
}
