package schema

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jackc/pgx/v5"

	"github.com/agim/lidza/pkg/decimal"
)

const orders = `model Customer {
  id   bigint @id @default(autoincrement())
  name string
}

model Order {
  id         int              @id @default(autoincrement())
  customerId bigint           @ref(Customer, cascade)
  total      decimal(12, 2)   @min(0.01) @max(99999999.99)
  discount   decimal(5,4)?    @default(0)
  rates      decimal(8, 3)[]
}

type Quote {
  amount decimal(20, 0) @min(-100000000000000000000)
}
`

// TestDecimalAndIdentity: decimal(p, s) is numeric(p,s) and an exact
// Go type; autoincrement() is an identity column.
func TestDecimalAndIdentity(t *testing.T) {
	s, err := Parse(orders)
	if err != nil {
		t.Fatal(err)
	}
	total := s.Model("Order").Fields[2]
	if total.Type != "decimal" || total.Precision != 12 || total.Scale != 2 || total.MinText != "0.01" || total.TypeText() != "decimal(12, 2)" {
		t.Fatalf("total: %+v", total)
	}
	ddl := GenerateSQL(s)
	for _, want := range []string{
		"id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY",
		"id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY",
		"customer_id bigint NOT NULL REFERENCES customer(id) ON DELETE CASCADE",
		"total numeric(12,2) NOT NULL",
		"discount numeric(5,4) DEFAULT 0",
		"rates numeric(8,3)[] NOT NULL",
	} {
		if !strings.Contains(ddl, want) {
			t.Errorf("DDL lacks %q:\n%s", want, ddl)
		}
	}

	src := GenerateGo(s)
	for _, want := range []string{
		`"github.com/agim/lidza/pkg/decimal"`,
		"Total decimal.Decimal `json:\"total\" db:\"total\"`",
		"Discount *decimal.Decimal",
		"Rates []decimal.Decimal",
		"ID int64 `json:\"id\"",
		`v.Total.Valid() && v.Total.Cmp("0.01") < 0`,
	} {
		if !strings.Contains(src, want) {
			t.Errorf("Go lacks %q:\n%s", want, src)
		}
	}
	if strings.Contains(GenerateGo(mustParse(example)), "pkg/decimal") {
		t.Error("decimal imported without a decimal field")
	}

	ts := GenerateTS(s)
	for _, want := range []string{"  total: string\n", "  discount: string | null\n", "  rates: string[]\n", "  id: number\n", `/** Exact decimal as a string, "12.50" (12 digits, 2 after the point). */`} {
		if !strings.Contains(ts, want) {
			t.Errorf("TS lacks %q:\n%s", want, ts)
		}
	}
	js := JSONSchema(s)["Order"].(map[string]any)["properties"].(map[string]any)
	if tot := js["total"].(map[string]any); tot["type"] != "string" || tot["format"] != "decimal" || tot["x-minimum"] != "0.01" || tot["x-maximum"] != "99999999.99" || tot["x-precision"] != 12 || tot["minimum"] != nil {
		t.Errorf("total: %v", tot)
	}
	if d := js["discount"].(map[string]any); d["type"].([]any)[1] != "null" || d["x-scale"] != 4 {
		t.Errorf("discount: %v", d)
	}
	rs := GenerateRust(s)
	for _, want := range []string{"pub total: String,", "pub discount: Option<String>,", "pub rates: Vec<String>,", "pub id: i64,"} {
		if !strings.Contains(rs, want) {
			t.Errorf("Rust lacks %q:\n%s", want, rs)
		}
	}

	for name, src := range map[string]string{
		"bare decimal":           "model A {\n id uuid @id\n p decimal\n}",
		"scale over precision":   "model A {\n id uuid @id\n p decimal(2, 3)\n}",
		"precision zero":         "model A {\n id uuid @id\n p decimal(0)\n}",
		"args on another type":   "model A {\n id uuid @id\n p int(4)\n}",
		"decimal min not plain":  "model A {\n id uuid @id\n p decimal(4, 2) @min(1e2)\n}",
		"decimal default":        "model A {\n id uuid @id\n p decimal(4, 2) @default(abc)\n}",
		"autoincrement uuid":     "model A {\n id uuid @id @default(autoincrement())\n}",
		"autoincrement optional": "model A {\n id uuid @id\n n int? @default(autoincrement())\n}",
		"autoincrement in type":  "type A {\n n int @default(autoincrement())\n}",
	} {
		if _, err := Parse(src); err == nil {
			t.Errorf("%s: expected an error", name)
		}
	}
	if _, err := Parse("model A {\n id int @id @default(autoincrement())\n}\nmodel B {\n id uuid @id\n aId uuid @ref(A)\n}"); err == nil || !strings.Contains(err.Error(), "needs type int") {
		t.Errorf("ref to an identity id: %v", err)
	}
}

// TestDiffDecimalAndIdentity: new decimal and identity columns on an
// existing table, and an existing column becoming an identity.
func TestDiffDecimalAndIdentity(t *testing.T) {
	v1 := mustParse("model Product {\n  id uuid @id @default(uuid())\n  seq bigint @default(0)\n}")
	v2 := mustParse("model Product {\n  id uuid @id @default(uuid())\n  seq bigint @default(autoincrement())\n  number int @default(autoincrement())\n  price decimal(10, 2) @default(\"0.00\")\n  weight decimal(6,3)?\n}")
	m := Diff(v1, v2, 2)
	if m == nil {
		t.Fatal("expected a migration")
	}
	up := strings.Join(m.Up, "\n")
	for _, want := range []string{
		"ALTER TABLE product ALTER COLUMN seq DROP DEFAULT;\nALTER TABLE product ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY;\nSELECT setval(pg_get_serial_sequence('product', 'seq'), coalesce(max(seq), 0) + 1, false) FROM product;",
		"ALTER TABLE product ADD COLUMN number integer NOT NULL GENERATED BY DEFAULT AS IDENTITY;",
		"ALTER TABLE product ADD COLUMN price numeric(10,2) NOT NULL DEFAULT '0.00';",
		"ALTER TABLE product ADD COLUMN weight numeric(6,3);",
	} {
		if !strings.Contains(up, want) {
			t.Errorf("up lacks %q:\n%s", want, up)
		}
	}
	down := strings.Join(m.Down, "\n")
	if !strings.Contains(down, "ALTER TABLE product ALTER COLUMN seq DROP IDENTITY;\nALTER TABLE product ALTER COLUMN seq SET DEFAULT 0;") {
		t.Errorf("down:\n%s", down)
	}
	back := strings.Join(Diff(v2, v1, 3).Up, "\n")
	if !strings.Contains(back, "ALTER TABLE product ALTER COLUMN seq DROP IDENTITY;\nALTER TABLE product ALTER COLUMN seq SET DEFAULT 0;") {
		t.Errorf("identity dropped:\n%s", back)
	}
	v3 := mustParse(strings.Replace("model Product {\n  id uuid @id @default(uuid())\n  seq bigint @default(autoincrement())\n  number int @default(autoincrement())\n  price decimal(10, 2) @default(\"0.00\")\n  weight decimal(6,3)?\n}", "decimal(10, 2)", "decimal(12, 4)", 1))
	if up := strings.Join(Diff(v2, v3, 3).Up, "\n"); !strings.Contains(up, "ALTER TABLE product ALTER COLUMN price TYPE numeric(12,4) USING price::numeric(12,4); -- review: was numeric(10,2)") {
		t.Errorf("precision change:\n%s", up)
	}
	if Diff(v2, v2, 3) != nil {
		t.Error("no change should give no migration")
	}
}

// TestDecimalPostgres applies the migrations of TestDiffDecimalAndIdentity
// to the test database (LIDZA_TEST_DATABASE_URL; skipped without one),
// inside a transaction it rolls back, and reads a decimal back through
// pgx without a float in between. (pgx reads a zero as 0 whatever its
// scale; every other value keeps its trailing zeros.)
func TestDecimalPostgres(t *testing.T) {
	url := os.Getenv("LIDZA_TEST_DATABASE_URL")
	if url == "" {
		url = "postgres:///lidza_test?host=/var/run/postgresql"
	}
	ctx := context.Background()
	conn, err := pgx.Connect(ctx, url)
	if err != nil {
		t.Skipf("no test database: %v", err)
	}
	defer conn.Close(ctx)
	tx, err := conn.Begin(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer tx.Rollback(ctx)
	v1 := mustParse("model Probe {\n  id uuid @id @default(uuid())\n  seq bigint @default(0)\n}")
	v2 := mustParse("model Probe {\n  id uuid @id @default(uuid())\n  seq bigint @default(autoincrement())\n  number int @default(autoincrement())\n  price decimal(30, 2) @default(\"0.00\")\n  weight decimal(6,3)?\n}")
	init, _ := Diff(nil, v1, 1).Files()
	up, down := Diff(v1, v2, 2).Files()
	for _, stmt := range []string{"DROP TABLE IF EXISTS probe", init, "INSERT INTO probe (seq) VALUES (7), (9)", up} {
		if _, err := tx.Exec(ctx, stmt); err != nil {
			t.Fatalf("%v\n%s", err, stmt)
		}
	}
	big := decimal.Decimal("1234567890123456789012345678.10")
	if _, err := tx.Exec(ctx, "INSERT INTO probe (price) VALUES ($1)", big); err != nil {
		t.Fatal(err)
	}
	rows, err := tx.Query(ctx, "SELECT seq, number, price, weight FROM probe ORDER BY seq")
	if err != nil {
		t.Fatal(err)
	}
	var got []string
	for rows.Next() {
		var seq int64
		var number int32
		var price decimal.Decimal
		var weight *decimal.Decimal
		if err := rows.Scan(&seq, &number, &price, &weight); err != nil {
			t.Fatal(err)
		}
		got = append(got, fmt.Sprintf("%d|%d|%s|%v", seq, number, price, weight))
	}
	if strings.Join(got, " ") != "7|1|0|<nil> 9|2|0|<nil> 10|3|1234567890123456789012345678.10|<nil>" {
		t.Errorf("rows: %v", got)
	}
	if _, err := tx.Exec(ctx, down); err != nil {
		t.Fatalf("down: %v\n%s", err, down)
	}
}

// TestGenerateGoDecimal compiles the Go package and runs its rules:
// exact bounds, digits that do not fit the column, JSON as strings.
func TestGenerateGoDecimal(t *testing.T) {
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("go not installed")
	}
	s := mustParse(orders)
	root, _ := filepath.Abs("../..")
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module app\n\ngo 1.27\n\nrequire github.com/agim/lidza v0.0.0\n\nreplace github.com/agim/lidza => "+root+"\n"), 0o644)
	os.MkdirAll(filepath.Join(dir, "schema"), 0o755)
	os.WriteFile(filepath.Join(dir, GoFile), []byte(Gofmt(GenerateGo(s))), 0o644)
	os.WriteFile(filepath.Join(dir, "main.go"), []byte(`package main

import (
	"encoding/json"
	"fmt"

	"app/schema"
	"github.com/agim/lidza/pkg/decimal"
	"github.com/agim/lidza/pkg/validate"
)

func rules(err error) string {
	if err == nil {
		return ""
	}
	out := ""
	for _, f := range err.(*validate.Errors).Fields {
		out += f.Field + ":" + f.Rule + " "
	}
	return out
}

func main() {
	d := decimal.Decimal("0.00005")
	for _, c := range []struct {
		o    schema.Order
		want string
	}{
		{schema.Order{Total: "0.01"}, ""},
		{schema.Order{Total: "0.009"}, "total:decimal total:min "},
		{schema.Order{Total: "0.00"}, "total:min "},
		{schema.Order{Total: "99999999.99"}, ""},
		{schema.Order{Total: "100000000.00"}, "total:max "},
		{schema.Order{Total: "10000000000.00"}, "total:decimal total:max "},
		{schema.Order{Total: "1", Discount: &d}, "discount:decimal "},
		{schema.Order{Total: "1", Rates: []decimal.Decimal{"1.5", "12345.6789"}}, "rates:decimal "},
		{schema.Order{Total: "abc"}, "total:decimal "},
	} {
		if got := rules(c.o.Validate()); got != c.want {
			panic(fmt.Sprintf("%+v: %q, want %q", c.o, got, c.want))
		}
	}
	if got := rules(schema.Quote{Amount: "-100000000000000000001"}.Validate()); got != "amount:decimal amount:min " {
		panic(got)
	}
	var o schema.Order
	if err := json.Unmarshal([]byte(`+"`"+`{"id":1,"customerId":2,"total":"12.50","discount":null,"rates":["0.125"]}`+"`"+`), &o); err != nil {
		panic(err)
	}
	b, _ := json.Marshal(o)
	fmt.Println(string(b))
}
`), 0o644)
	for _, args := range [][]string{{"mod", "tidy"}, {"vet", "./..."}, {"run", "."}} {
		cmd := exec.Command("go", args...)
		cmd.Dir = dir
		cmd.Env = append(os.Environ(), "GOFLAGS=-mod=mod")
		out, err := cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("go %v: %v\n%s", args, err, out)
		}
		if args[0] == "run" && strings.TrimSpace(string(out)) != `{"id":1,"customerId":2,"total":"12.50","discount":null,"rates":["0.125"]}` {
			t.Fatalf("run: %s", out)
		}
	}
}
