package schema

import (
	"fmt"
	"strings"
)

// GenerateTS renders the TypeScript types: enums as string literal unions
// with a values array, models and types as interfaces. Optional fields are
// `T | null` because the Go side encodes a nil pointer as null. A decimal
// is a string ("12.50"), exact as the server sent it.
func GenerateTS(s *Schema) string {
	var b strings.Builder
	b.WriteString("// Code generated by lidza gen from " + FileName + ". DO NOT EDIT.\n\n")
	for _, e := range s.Enums {
		vals := make([]string, len(e.Values))
		for i, v := range e.Values {
			vals[i] = fmt.Sprintf("%q", v)
		}
		fmt.Fprintf(&b, "export type %s = %s\n", e.Name, strings.Join(vals, " | "))
		fmt.Fprintf(&b, "export const %sValues: readonly %s[] = [%s] as const\n\n", e.Name, e.Name, strings.Join(vals, ", "))
	}
	for _, m := range append(append([]*Model{}, s.Models...), s.Types...) {
		fmt.Fprintf(&b, "export interface %s {\n", m.Name)
		for _, f := range m.Fields {
			switch f.Type {
			case "decimal":
				fmt.Fprintf(&b, "  /** Exact decimal as a string, \"12.50\" (%d digits, %d after the point). */\n", f.Precision, f.Scale)
			case "date":
				b.WriteString("  /** Calendar day, \"2026-10-06\": no time zone, never shift it. */\n")
			case "localtime":
				b.WriteString("  /** Local date and time as typed, \"2026-10-06T10:30\" (no zone): the server reads it in the visitor's zone. */\n")
			}
			fmt.Fprintf(&b, "  %s: %s\n", f.Name, tsType(f))
		}
		b.WriteString("}\n\n")
	}
	return b.String()
}

func tsType(f *Field) string {
	var t string
	switch f.Type {
	case "string", "text", "uuid", "time", "date", "localtime", "bytes", "decimal":
		t = "string"
	case "int", "bigint", "float":
		t = "number"
	case "bool":
		t = "boolean"
	case "json":
		t = "unknown"
	default:
		t = f.Type
	}
	if f.Array {
		t += "[]"
		if f.Optional {
			t += " | null"
		}
		return t
	}
	if f.Optional {
		return t + " | null"
	}
	return t
}

// JSONSchema renders the JSON Schema (2020-12) definitions for every enum,
// model and type, keyed by name, for OpenAPI's components.schemas.
func JSONSchema(s *Schema) map[string]any {
	defs := map[string]any{}
	for _, e := range s.Enums {
		defs[e.Name] = map[string]any{"type": "string", "enum": e.Values}
	}
	for _, m := range append(append([]*Model{}, s.Models...), s.Types...) {
		props := map[string]any{}
		var required []string
		for _, f := range m.Fields {
			props[f.Name] = jsonSchemaType(s, f)
			// An optional field may be omitted as well as null: the Go
			// side decodes both as nil, the TypeScript side gets `?`.
			if !f.Optional {
				required = append(required, f.Name)
			}
		}
		// x-lidza marks definitions that carry validation rules, so the
		// client generates validators for them and not for plain Go types.
		defs[m.Name] = map[string]any{"type": "object", "properties": props, "required": required, "x-lidza": "schema"}
	}
	return defs
}

// LocalTimePattern is the JSON Schema pattern of a localtime field: what
// an HTML datetime-local input sends, with optional seconds.
const LocalTimePattern = `^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(:\d{2})?$`

// DecimalPattern is the JSON Schema pattern of a decimal field: plain
// notation, an optional sign and fraction.
const DecimalPattern = `^[+-]?[0-9]+(\.[0-9]+)?$`

func jsonSchemaType(s *Schema, f *Field) map[string]any {
	var t map[string]any
	switch f.Type {
	case "string", "text":
		t = map[string]any{"type": "string"}
		if f.Min != nil {
			t["minLength"] = *f.Min
		}
		if f.Max != nil {
			t["maxLength"] = *f.Max
		}
		if f.Email {
			t["format"] = "email"
		}
		if f.URL {
			t["format"] = "uri"
		}
		if f.Pattern != "" {
			t["pattern"] = f.Pattern
		}
		if f.Timezone {
			t["x-format"] = "timezone"
		}
	case "uuid":
		t = map[string]any{"type": "string", "format": "uuid"}
	case "time":
		t = map[string]any{"type": "string", "format": "date-time"}
	case "date":
		t = map[string]any{"type": "string", "format": "date"}
	case "localtime":
		// A wall-clock time with no offset: not RFC 3339's date-time.
		t = map[string]any{"type": "string", "pattern": LocalTimePattern, "x-format": "local-date-time"}
	case "bytes":
		t = map[string]any{"type": "string", "contentEncoding": "base64"}
	case "int":
		t = map[string]any{"type": "integer", "format": "int32"}
	case "bigint":
		t = map[string]any{"type": "integer", "format": "int64"}
	case "float":
		t = map[string]any{"type": "number", "format": "double"}
	case "decimal":
		// A string, so no client reads it into a binary float; the x-
		// keywords carry the column's digits and the exact bounds for
		// the generated validators.
		t = map[string]any{"type": "string", "format": "decimal", "pattern": DecimalPattern, "x-precision": f.Precision, "x-scale": f.Scale}
		if f.MinText != "" {
			t["x-minimum"] = f.MinText
		}
		if f.MaxText != "" {
			t["x-maximum"] = f.MaxText
		}
	case "bool":
		t = map[string]any{"type": "boolean"}
	case "json":
		t = map[string]any{}
	default:
		t = map[string]any{"$ref": "#/components/schemas/" + f.Type}
	}
	if (f.Type == "int" || f.Type == "bigint" || f.Type == "float") && !f.Array {
		if f.Min != nil {
			t["minimum"] = *f.Min
		}
		if f.Max != nil {
			t["maximum"] = *f.Max
		}
	}
	if f.Array {
		arr := map[string]any{"type": "array", "items": t}
		if f.Min != nil {
			arr["minItems"] = *f.Min
		}
		if f.Max != nil {
			arr["maxItems"] = *f.Max
		}
		t = arr
	}
	if f.Optional {
		if ref, ok := t["$ref"]; ok {
			t = map[string]any{"oneOf": []any{map[string]any{"$ref": ref}, map[string]any{"type": "null"}}}
		} else if typ, ok := t["type"]; ok {
			t["type"] = []any{typ, "null"}
		}
	}
	return t
}
