package schema

import (
	"fmt"
	"strconv"
	"strings"
)

// GoPackage is the package name of the generated Go file.
const GoPackage = "schema"

// GoFile is the generated Go source, relative to the project root.
const GoFile = "schema/schema.go"

// GenerateGo renders the Go package: enums as string types with constants,
// models and types as structs with json and db tags, and a Validate method
// per struct that applies the field rules.
func GenerateGo(s *Schema) string {
	var b strings.Builder
	b.WriteString("// Code generated by lidza gen from " + FileName + ". DO NOT EDIT.\n\n")
	b.WriteString("package " + GoPackage + "\n\n")

	imports := []string{`"github.com/agim/lidza/pkg/validate"`}
	if usesGo(s, "time", "date") {
		imports = append(imports, `"time"`)
	}
	if usesGo(s, "json") {
		imports = append(imports, `"encoding/json"`)
	}
	b.WriteString("import (\n")
	for _, imp := range imports {
		b.WriteString("\t" + imp + "\n")
	}
	b.WriteString(")\n\n")

	for _, e := range s.Enums {
		fmt.Fprintf(&b, "// %s is the %s enum.\ntype %s string\n\n", e.Name, e.Name, e.Name)
		b.WriteString("const (\n")
		for _, v := range e.Values {
			fmt.Fprintf(&b, "\t%s%s %s = %q\n", e.Name, exported(v), e.Name, v)
		}
		b.WriteString(")\n\n")
		fmt.Fprintf(&b, "// %sValues lists every %s.\nvar %sValues = []%s{", e.Name, e.Name, e.Name, e.Name)
		for i, v := range e.Values {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(e.Name + exported(v))
		}
		b.WriteString("}\n\n")
		fmt.Fprintf(&b, "// Valid reports whether v is one of the %s values.\nfunc (v %s) Valid() bool {\n\tfor _, x := range %sValues {\n\t\tif v == x {\n\t\t\treturn true\n\t\t}\n\t}\n\treturn false\n}\n\n", e.Name, e.Name, e.Name)
	}

	for _, m := range append(append([]*Model{}, s.Models...), s.Types...) {
		if m.Persisted {
			fmt.Fprintf(&b, "// %s is a row of the %s table.\n", m.Name, m.Table)
		} else {
			fmt.Fprintf(&b, "// %s is an API type.\n", m.Name)
		}
		fmt.Fprintf(&b, "type %s struct {\n", m.Name)
		for _, f := range m.Fields {
			tag := fmt.Sprintf("`json:\"%s\"", f.Name)
			if m.Persisted {
				tag += fmt.Sprintf(" db:\"%s\"", snake(f.Name))
			}
			tag += "`"
			fmt.Fprintf(&b, "\t%s %s %s\n", exported(f.Name), goType(s, f), tag)
		}
		b.WriteString("}\n\n")
		writeGoValidate(&b, s, m)
	}
	return b.String()
}

func usesGo(s *Schema, types ...string) bool {
	for _, m := range append(append([]*Model{}, s.Models...), s.Types...) {
		for _, f := range m.Fields {
			for _, t := range types {
				if f.Type == t {
					return true
				}
			}
		}
	}
	return false
}

// goType maps a field to its Go type: optional fields are pointers, arrays
// slices (an optional array is a nil-able slice, not a pointer to one).
func goType(s *Schema, f *Field) string {
	var t string
	switch f.Type {
	case "string", "text", "uuid":
		t = "string"
	case "int":
		t = "int"
	case "bigint":
		t = "int64"
	case "float":
		t = "float64"
	case "bool":
		t = "bool"
	case "time", "date":
		t = "time.Time"
	case "json":
		t = "json.RawMessage"
	case "bytes":
		t = "[]byte"
	default:
		t = f.Type // enum or type
	}
	if f.Array {
		return "[]" + t
	}
	if f.Optional && f.Type != "json" && f.Type != "bytes" {
		return "*" + t
	}
	return t
}

// writeGoValidate emits Validate for the struct. Rules: required (a non-
// optional string, text, uuid or enum must not be empty), min and max
// (length for strings and arrays, value for numbers), email, url, pattern,
// enum membership, and nested Validate for type-valued fields.
func writeGoValidate(b *strings.Builder, s *Schema, m *Model) {
	fmt.Fprintf(b, "// Validate applies the rules of %s from %s.\nfunc (v %s) Validate() error {\n\tvar errs validate.Errors\n", m.Name, FileName, m.Name)
	for _, f := range m.Fields {
		field := "v." + exported(f.Name)
		isStr := f.Type == "string" || f.Type == "text" || f.Type == "uuid"
		isNum := f.Type == "int" || f.Type == "bigint" || f.Type == "float"
		isEnum := s.Enum(f.Type) != nil
		isType := s.Model(f.Type) != nil && !m.Persisted

		// rule appends one "if cond { errs.Add(...) }" for the field.
		var rules []string
		rule := func(cond, kind, msg string) {
			rules = append(rules, fmt.Sprintf("if %s {\n\terrs.Add(%q, %q, %q)\n}", cond, f.Name, kind, msg))
		}

		if f.Array {
			if f.Min != nil {
				rule(fmt.Sprintf("len(%s) < %s", field, fnum(*f.Min)), "min", "at least "+fnum(*f.Min)+" item(s)")
			}
			if f.Max != nil {
				rule(fmt.Sprintf("len(%s) > %s", field, fnum(*f.Max)), "max", "at most "+fnum(*f.Max)+" item(s)")
			}
			if isEnum {
				rules = append(rules, fmt.Sprintf("for _, x := range %s {\n\tif !x.Valid() {\n\t\terrs.Add(%q, \"enum\", \"unknown %s value\")\n\t\tbreak\n\t}\n}", field, f.Name, f.Type))
			}
			if isType {
				rules = append(rules, fmt.Sprintf("for _, x := range %s {\n\tif err := x.Validate(); err != nil {\n\t\terrs.Add(%q, \"nested\", err.Error())\n\t\tbreak\n\t}\n}", field, f.Name))
			}
			for _, r := range rules {
				b.WriteString(indent(r, 1))
			}
			continue
		}

		// Optional scalars are pointers: the rules run on the value when set.
		val := field
		deref := f.Optional && f.Type != "json" && f.Type != "bytes"
		if deref {
			val = "x"
		}
		switch {
		case isStr:
			if !f.Optional && !f.ID {
				rule(val+` == ""`, "required", "required")
			}
			if f.Min != nil {
				rule(fmt.Sprintf("len(%s) < %s", val, fnum(*f.Min)), "min", "at least "+fnum(*f.Min)+" character(s)")
			}
			if f.Max != nil {
				rule(fmt.Sprintf("len(%s) > %s", val, fnum(*f.Max)), "max", "at most "+fnum(*f.Max)+" character(s)")
			}
			if f.Email {
				rule(fmt.Sprintf(`%s != "" && !validate.Email(%s)`, val, val), "email", "not an email address")
			}
			if f.URL {
				rule(fmt.Sprintf(`%s != "" && !validate.URL(%s)`, val, val), "url", "not an http(s) URL")
			}
			if f.Pattern != "" {
				rule(fmt.Sprintf(`%s != "" && !validate.Pattern(%s, %s)`, val, strconv.Quote(f.Pattern), val), "pattern", "does not match "+f.Pattern)
			}
		case isNum:
			if f.Min != nil {
				rule(fmt.Sprintf("%s < %s", val, fnum(*f.Min)), "min", "at least "+fnum(*f.Min))
			}
			if f.Max != nil {
				rule(fmt.Sprintf("%s > %s", val, fnum(*f.Max)), "max", "at most "+fnum(*f.Max))
			}
		case isEnum:
			if !f.Optional {
				rule(val+` == ""`, "required", "required")
			}
			rule(fmt.Sprintf(`%s != "" && !%s.Valid()`, val, val), "enum", "unknown "+f.Type+" value")
		case isType:
			rules = append(rules, fmt.Sprintf("if err := %s.Validate(); err != nil {\n\terrs.Add(%q, \"nested\", err.Error())\n}", val, f.Name))
		}
		if len(rules) == 0 {
			continue
		}
		if deref {
			fmt.Fprintf(b, "\tif %s != nil {\n\t\tx := *%s\n", field, field)
			for _, r := range rules {
				b.WriteString(indent(r, 2))
			}
			b.WriteString("\t}\n")
		} else {
			for _, r := range rules {
				b.WriteString(indent(r, 1))
			}
		}
	}
	b.WriteString("\treturn errs.Result()\n}\n\n")
}

// indent prefixes every line of s with n tabs and ends it with a newline.
func indent(s string, n int) string {
	pad := strings.Repeat("\t", n)
	lines := strings.Split(s, "\n")
	for i, l := range lines {
		lines[i] = pad + l
	}
	return strings.Join(lines, "\n") + "\n"
}

// fnum prints a number the way a Go literal needs it: 200 stays 200, 0.5
// stays 0.5.
func fnum(v float64) string {
	return strconv.FormatFloat(v, 'f', -1, 64)
}
