package schema

import (
	"fmt"
	"strconv"
	"strings"
)

// SQLFile is the full DDL of the current schema, relative to the project
// root. It is regenerated on every `lidza gen`; sqlc reads it.
const SQLFile = "db/schema.sql"

// GenerateSQL renders the Postgres DDL for every enum and model.
func GenerateSQL(s *Schema) string {
	var b strings.Builder
	b.WriteString("-- Code generated by lidza gen from " + FileName + ". DO NOT EDIT.\n")
	b.WriteString("-- The current schema in full; migrations in db/migrations carry the changes.\n\n")
	for _, e := range s.Enums {
		b.WriteString(createEnum(e) + "\n\n")
	}
	for _, m := range s.Models {
		b.WriteString(createTable(s, m) + "\n")
		for _, stmt := range createIndexes(m) {
			b.WriteString(stmt + "\n")
		}
		b.WriteString("\n")
	}
	return b.String()
}

func createEnum(e *Enum) string {
	vals := make([]string, len(e.Values))
	for i, v := range e.Values {
		vals[i] = quoteLit(v)
	}
	return fmt.Sprintf("CREATE TYPE %s AS ENUM (%s);", snake(e.Name), strings.Join(vals, ", "))
}

func createTable(s *Schema, m *Model) string {
	var cols []string
	for _, f := range m.Fields {
		cols = append(cols, "  "+columnDef(s, f))
	}
	return fmt.Sprintf("CREATE TABLE %s (\n%s\n);", qid(m.Table), strings.Join(cols, ",\n"))
}

// reserved are the Postgres keywords a table or column may collide with;
// qid quotes them.
var reserved = map[string]bool{
	"all": true, "and": true, "any": true, "as": true, "asc": true, "check": true, "column": true,
	"constraint": true, "create": true, "default": true, "desc": true, "distinct": true, "do": true,
	"else": true, "end": true, "from": true, "grant": true, "group": true, "having": true, "in": true,
	"into": true, "limit": true, "not": true, "null": true, "offset": true, "on": true, "only": true,
	"or": true, "order": true, "primary": true, "references": true, "select": true, "table": true,
	"then": true, "to": true, "union": true, "unique": true, "user": true, "using": true, "when": true,
	"where": true, "with": true,
}

// qid quotes an identifier when it is a reserved word.
func qid(name string) string {
	if reserved[name] {
		return `"` + name + `"`
	}
	return name
}

// col is the quoted column name of a field.
func col(f *Field) string { return qid(snake(f.Name)) }

// columnDef renders "name type [NOT NULL] [DEFAULT v] [PRIMARY KEY|UNIQUE] [REFERENCES t(id)]".
func columnDef(s *Schema, f *Field) string {
	parts := []string{col(f), sqlType(s, f)}
	if f.ID {
		parts = append(parts, "PRIMARY KEY")
	} else {
		if !f.Optional {
			parts = append(parts, "NOT NULL")
		}
		if f.Unique {
			parts = append(parts, "UNIQUE")
		}
	}
	if f.Default != "" {
		parts = append(parts, "DEFAULT "+sqlDefault(s, f))
	}
	if ref := references(s, f); ref != "" {
		parts = append(parts, ref)
	}
	return strings.Join(parts, " ")
}

func sqlType(s *Schema, f *Field) string {
	var t string
	switch f.Type {
	case "string":
		if f.Max != nil && !f.Array {
			t = "varchar(" + fnum(*f.Max) + ")"
		} else {
			t = "text"
		}
	case "text":
		t = "text"
	case "int":
		t = "integer"
	case "bigint":
		t = "bigint"
	case "float":
		t = "double precision"
	case "bool":
		t = "boolean"
	case "time":
		t = "timestamptz"
	case "date":
		t = "date"
	case "uuid":
		t = "uuid"
	case "json":
		t = "jsonb"
	case "bytes":
		t = "bytea"
	default:
		t = snake(f.Type) // enum
	}
	if f.Array {
		return t + "[]"
	}
	return t
}

// sqlDefault maps the schema default to SQL: uuid() and now() to the
// Postgres functions, enum values and strings to literals, the rest as is.
func sqlDefault(s *Schema, f *Field) string {
	switch f.Default {
	case "uuid()":
		return "gen_random_uuid()"
	case "now()":
		return "now()"
	}
	if s.Enum(f.Type) != nil {
		return quoteLit(f.Default)
	}
	if strings.HasPrefix(f.Default, `"`) {
		if v, err := strconv.Unquote(f.Default); err == nil {
			return quoteLit(v)
		}
	}
	return f.Default
}

func createIndexes(m *Model) []string {
	var out []string
	for _, f := range m.Fields {
		if f.Index && !f.Unique && !f.ID {
			out = append(out, fmt.Sprintf("CREATE INDEX %s ON %s (%s);", indexName(m, []string{f.Name}, false), qid(m.Table), col(f)))
		}
	}
	for _, ix := range m.Indexes {
		cols := make([]string, len(ix.Fields))
		for i, f := range ix.Fields {
			cols[i] = qid(snake(f))
		}
		kind := "INDEX"
		if ix.Unique {
			kind = "UNIQUE INDEX"
		}
		out = append(out, fmt.Sprintf("CREATE %s %s ON %s (%s);", kind, indexName(m, ix.Fields, ix.Unique), qid(m.Table), strings.Join(cols, ", ")))
	}
	return out
}

func indexName(m *Model, fields []string, unique bool) string {
	cols := make([]string, len(fields))
	for i, f := range fields {
		cols[i] = snake(f)
	}
	suffix := "_idx"
	if unique {
		suffix = "_key"
	}
	return m.Table + "_" + strings.Join(cols, "_") + suffix
}

func quoteLit(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// references is the foreign-key clause of a field, "" without @ref.
func references(s *Schema, f *Field) string {
	if f.Ref == "" {
		return ""
	}
	target := s.Model(f.Ref)
	if target == nil {
		return ""
	}
	ref := fmt.Sprintf("REFERENCES %s(%s)", qid(target.Table), col(target.IDField()))
	switch f.OnDelete {
	case "cascade":
		ref += " ON DELETE CASCADE"
	case "setnull":
		ref += " ON DELETE SET NULL"
	}
	return ref
}
