package schema

import (
	"fmt"
	"strings"
)

// GenerateTS renders the TypeScript types: enums as string literal unions
// with a values array, models and types as interfaces. Optional fields are
// `T | null` because the Go side encodes a nil pointer as null.
func GenerateTS(s *Schema) string {
	var b strings.Builder
	b.WriteString("// Code generated by lidza gen from " + FileName + ". DO NOT EDIT.\n\n")
	for _, e := range s.Enums {
		vals := make([]string, len(e.Values))
		for i, v := range e.Values {
			vals[i] = fmt.Sprintf("%q", v)
		}
		fmt.Fprintf(&b, "export type %s = %s\n", e.Name, strings.Join(vals, " | "))
		fmt.Fprintf(&b, "export const %sValues: readonly %s[] = [%s] as const\n\n", e.Name, e.Name, strings.Join(vals, ", "))
	}
	for _, m := range append(append([]*Model{}, s.Models...), s.Types...) {
		fmt.Fprintf(&b, "export interface %s {\n", m.Name)
		for _, f := range m.Fields {
			fmt.Fprintf(&b, "  %s: %s\n", f.Name, tsType(f))
		}
		b.WriteString("}\n\n")
	}
	return b.String()
}

func tsType(f *Field) string {
	var t string
	switch f.Type {
	case "string", "text", "uuid", "time", "date", "bytes":
		t = "string"
	case "int", "bigint", "float":
		t = "number"
	case "bool":
		t = "boolean"
	case "json":
		t = "unknown"
	default:
		t = f.Type
	}
	if f.Array {
		t += "[]"
		if f.Optional {
			t += " | null"
		}
		return t
	}
	if f.Optional {
		return t + " | null"
	}
	return t
}

// JSONSchema renders the JSON Schema (2020-12) definitions for every enum,
// model and type, keyed by name, for OpenAPI's components.schemas.
func JSONSchema(s *Schema) map[string]any {
	defs := map[string]any{}
	for _, e := range s.Enums {
		defs[e.Name] = map[string]any{"type": "string", "enum": e.Values}
	}
	for _, m := range append(append([]*Model{}, s.Models...), s.Types...) {
		props := map[string]any{}
		var required []string
		for _, f := range m.Fields {
			props[f.Name] = jsonSchemaType(s, f)
			required = append(required, f.Name)
		}
		defs[m.Name] = map[string]any{"type": "object", "properties": props, "required": required}
	}
	return defs
}

func jsonSchemaType(s *Schema, f *Field) map[string]any {
	var t map[string]any
	switch f.Type {
	case "string", "text":
		t = map[string]any{"type": "string"}
		if f.Min != nil {
			t["minLength"] = *f.Min
		}
		if f.Max != nil {
			t["maxLength"] = *f.Max
		}
		if f.Email {
			t["format"] = "email"
		}
		if f.URL {
			t["format"] = "uri"
		}
		if f.Pattern != "" {
			t["pattern"] = f.Pattern
		}
	case "uuid":
		t = map[string]any{"type": "string", "format": "uuid"}
	case "time":
		t = map[string]any{"type": "string", "format": "date-time"}
	case "date":
		t = map[string]any{"type": "string", "format": "date"}
	case "bytes":
		t = map[string]any{"type": "string", "contentEncoding": "base64"}
	case "int":
		t = map[string]any{"type": "integer", "format": "int32"}
	case "bigint":
		t = map[string]any{"type": "integer", "format": "int64"}
	case "float":
		t = map[string]any{"type": "number", "format": "double"}
	case "bool":
		t = map[string]any{"type": "boolean"}
	case "json":
		t = map[string]any{}
	default:
		t = map[string]any{"$ref": "#/components/schemas/" + f.Type}
	}
	if (f.Type == "int" || f.Type == "bigint" || f.Type == "float") && !f.Array {
		if f.Min != nil {
			t["minimum"] = *f.Min
		}
		if f.Max != nil {
			t["maximum"] = *f.Max
		}
	}
	if f.Array {
		arr := map[string]any{"type": "array", "items": t}
		if f.Min != nil {
			arr["minItems"] = *f.Min
		}
		if f.Max != nil {
			arr["maxItems"] = *f.Max
		}
		t = arr
	}
	if f.Optional {
		if ref, ok := t["$ref"]; ok {
			t = map[string]any{"oneOf": []any{map[string]any{"$ref": ref}, map[string]any{"type": "null"}}}
		} else if typ, ok := t["type"]; ok {
			t["type"] = []any{typ, "null"}
		}
	}
	return t
}
