package schema

import (
	"fmt"
	"strings"
)

// RustFile is the generated Rust module, relative to the crate directory.
// The crate needs `serde = { version = "1", features = ["derive"] }` and
// `mod schema;` in lib.rs.
const RustFile = "src/schema.rs"

// GenerateRust renders serde structs and enums. Time, date and uuid fields
// are strings, so the crate needs no chrono or uuid dependency; packs that
// want typed values convert at the boundary. Bytes fields are Vec<u8>
// carried as base64 (the JSON form Go uses), through the b64 helpers the
// file defines when it needs them (crate dependency: base64).
func GenerateRust(s *Schema) string {
	var b strings.Builder
	b.WriteString("// Code generated by lidza gen from " + FileName + ". DO NOT EDIT.\n\n")
	b.WriteString("#![allow(dead_code)]\n\nuse serde::{Deserialize, Serialize};\n\n")
	if usesGo(s, "bytes") {
		b.WriteString(rustB64)
	}
	for _, e := range s.Enums {
		fmt.Fprintf(&b, "#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]\npub enum %s {\n", e.Name)
		for _, v := range e.Values {
			fmt.Fprintf(&b, "    #[serde(rename = %q)]\n    %s,\n", v, exported(v))
		}
		b.WriteString("}\n\n")
	}
	for _, m := range append(append([]*Model{}, s.Models...), s.Types...) {
		fmt.Fprintf(&b, "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\npub struct %s {\n", m.Name)
		for _, f := range m.Fields {
			name := snake(f.Name)
			if name != f.Name {
				fmt.Fprintf(&b, "    #[serde(rename = %q)]\n", f.Name)
			}
			if f.Type == "bytes" && !f.Array {
				if f.Optional {
					b.WriteString("    #[serde(with = \"b64opt\", default)]\n")
				} else {
					b.WriteString("    #[serde(with = \"b64\")]\n")
				}
			}
			fmt.Fprintf(&b, "    pub %s: %s,\n", rustIdent(name), rustType(f))
		}
		b.WriteString("}\n\n")
	}
	return b.String()
}

func rustType(f *Field) string {
	var t string
	switch f.Type {
	case "string", "text", "uuid", "time", "date":
		t = "String"
	case "int":
		t = "i32"
	case "bigint":
		t = "i64"
	case "float":
		t = "f64"
	case "bool":
		t = "bool"
	case "json":
		t = "serde_json::Value"
	case "bytes":
		t = "Vec<u8>"
	default:
		t = f.Type
	}
	if f.Array {
		t = "Vec<" + t + ">"
	}
	if f.Optional {
		t = "Option<" + t + ">"
	}
	return t
}

var rustKeywords = map[string]bool{"type": true, "ref": true, "match": true, "mod": true, "use": true, "self": true, "super": true, "crate": true, "move": true, "box": true, "impl": true, "trait": true, "where": true, "loop": true, "async": true, "await": true, "dyn": true}

func rustIdent(s string) string {
	if rustKeywords[s] {
		return "r#" + s
	}
	return s
}

// rustB64 carries Vec<u8> as base64 strings, matching Go's []byte JSON.
const rustB64 = `mod b64 {
    use base64::{engine::general_purpose::STANDARD, Engine};
    use serde::{Deserialize, Deserializer, Serializer};

    pub fn serialize<S: Serializer>(v: &Vec<u8>, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(&STANDARD.encode(v))
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<Vec<u8>, D::Error> {
        let s = String::deserialize(d)?;
        STANDARD.decode(s).map_err(serde::de::Error::custom)
    }
}

mod b64opt {
    use base64::{engine::general_purpose::STANDARD, Engine};
    use serde::{Deserialize, Deserializer, Serializer};

    pub fn serialize<S: Serializer>(v: &Option<Vec<u8>>, s: S) -> Result<S::Ok, S::Error> {
        match v {
            Some(b) => s.serialize_some(&STANDARD.encode(b)),
            None => s.serialize_none(),
        }
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<Option<Vec<u8>>, D::Error> {
        let s: Option<String> = Option::deserialize(d)?;
        s.map(|s| STANDARD.decode(s).map_err(serde::de::Error::custom)).transpose()
    }
}

`
