// Code generated by lidza gen from lidza.json. DO NOT EDIT.

package main

import (
	"github.com/agim/lidza"

	auth "github.com/agim/lidza/packs/auth"
	db "github.com/agim/lidza/packs/db"
	llm "github.com/agim/lidza/packs/llm"
	mail "github.com/agim/lidza/packs/mail"
	storage "github.com/agim/lidza/packs/storage"
	stats "notes/packs/stats"
)

// packs lists the packs lidza.json enables, started in this order.
func packs() []lidza.Pack {
	return []lidza.Pack{
		db.Pack(),
		auth.Pack(),
		stats.Pack(),
		mail.Pack(),
		llm.Pack(),
		storage.Pack(),
	}
}
