package diag

import (
	"context"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

func TestRules(t *testing.T) {
	dir := t.TempDir()
	write := func(name, body string) {
		os.MkdirAll(filepath.Dir(filepath.Join(dir, name)), 0o755)
		os.WriteFile(filepath.Join(dir, name), []byte(body), 0o644)
	}
	write("app.go", `package main

import (
	"context"
	"net/http"

	"github.com/agim/lidza/pkg/router"
)

var sessions = map[string]int{}
var cache = make(map[string][]byte)
// lidza:ignore L001 (read only)
var lookup = map[string]int{}
var recent []string
var limit = 10
var mu sync.Mutex

func raw(w http.ResponseWriter, r *http.Request) {
	go func() {}()
}

func typed(ctx context.Context, req *router.Request[router.None]) (int, error) {
	go work()
	return 0, nil
}

func work() { go func() {}(); os.WriteFile("upload.bin", nil, 0o644) }

var apiKey = "sk-ant-api03-abcdefghijklmnopqrstuvwxyz0123456789"
`)
	write("handlers/things.go", `package handlers

import (
	"context"

	"github.com/agim/lidza/pkg/orm"
	"github.com/agim/lidza/pkg/router"
	_ "github.com/sendgrid/sendgrid-go/helpers/mail"
	_ "github.com/tmc/langchaingo/llms"
	_ "github.com/minio/minio-go/v7"
	_ "golang.org/x/oauth2/google"

	"app/schema"
	"app/db/queries"
)

type adHoc struct{ N int }

func ok(ctx context.Context, req *router.Request[schema.CreateThing]) ([]schema.Thing, error) { return nil, nil }
func okMap(ctx context.Context, req *router.Request[router.None]) (map[string]*schema.Thing, error) { return nil, nil }
func leak(ctx context.Context, req *router.Request[queries.Thing]) (adHoc, error) { return adHoc{}, nil }
func anon(ctx context.Context, req *router.Request[struct{ A int }]) (any, error) { return nil, nil }
func helper[In any](req *router.Request[In], n int) (In, error) { var z In; return z, nil }
`)
	write("gen.go", "// Code generated by x. DO NOT EDIT.\n\npackage main\n\nvar generated = map[string]int{}\n")
	write("app_test.go", "package main\n\nvar inTest = map[string]int{}\n")
	write("node_modules/x/x.go", "package x\n\nvar ignored = map[string]int{}\n")

	os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module app\n\ngo 1.27\n\nrequire github.com/agim/lidza v0.0.0\n\nreplace github.com/agim/lidza => "+frameworkRoot(t)+"\n"), 0o644)

	got := Rules(context.Background(), dir)
	var lines []string
	for _, d := range got {
		lines = append(lines, d.Code+" "+d.File+":"+itoa(d.Line)+" "+d.Severity)
	}
	want := "L001 app.go:10 warning,L001 app.go:11 warning,L001 app.go:14 warning,L002 app.go:19 warning,L002 app.go:23 warning,L009 app.go:27 warning,L010 app.go:29 warning," +
		"L004 handlers/things.go:6 error,L006 handlers/things.go:8 warning,L007 handlers/things.go:9 warning,L008 handlers/things.go:10 warning,L013 handlers/things.go:11 warning,L005 handlers/things.go:21 warning,L005 handlers/things.go:21 warning,L005 handlers/things.go:22 warning,L005 handlers/things.go:22 warning"
	if strings.Join(lines, ",") != want {
		t.Fatalf("got %v\nwant %s", lines, want)
	}
	for _, d := range got {
		if d.Layer != "go" {
			t.Fatalf("layer: %+v", d)
		}
		if d.Code == "L004" && !strings.Contains(d.Message, "did you mean github.com/agim/lidza/pkg/router") && !strings.Contains(d.Message, "does not exist") {
			t.Fatalf("L004 message: %s", d.Message)
		}
		if d.Code == "L005" && d.Line == 22 && !strings.Contains(d.Message, "struct{...}") && !strings.Contains(d.Message, "any") {
			t.Fatalf("L005 message: %s", d.Message)
		}
	}
}

func frameworkRoot(t *testing.T) string {
	t.Helper()
	root, err := filepath.Abs("../..")
	if err != nil {
		t.Fatal(err)
	}
	return root
}

func itoa(n int) string { return strconv.Itoa(n) }

func TestUnusedPack(t *testing.T) {
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, "lidza.json"), []byte(`{"name":"x","frontend":{"template":"react","dev":"npm run dev","url":"http://127.0.0.1:5173","dist":"dist"},"packs":["lidza/db","lidza/llm","lidza/storage"]}`), 0o644)
	os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module app\n\ngo 1.27\n\nrequire github.com/agim/lidza v0.0.0\n\nreplace github.com/agim/lidza => "+frameworkRoot(t)+"\n"), 0o644)
	os.WriteFile(filepath.Join(dir, "packs.go"), []byte("// Code generated by lidza gen from lidza.json. DO NOT EDIT.\n\npackage main\n\nimport (\n\t_ \"github.com/agim/lidza/packs/llm\"\n\t_ \"github.com/agim/lidza/packs/storage\"\n)\n"), 0o644)
	os.WriteFile(filepath.Join(dir, "routes.go"), []byte("package main\n\nimport _ \"github.com/agim/lidza/packs/llm\"\n"), 0o644)
	var codes []string
	for _, d := range Rules(context.Background(), dir) {
		if d.Code == "L011" {
			codes = append(codes, d.Message[:len("pack storage")])
		}
	}
	if strings.Join(codes, ",") != "pack storage" {
		t.Fatalf("L011: %v", codes)
	}
}

func TestMissingDecisions(t *testing.T) {
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, "lidza.json"), []byte(`{"name":"x","frontend":{"template":"react","dev":"npm run dev","url":"http://127.0.0.1:5173","dist":"dist"},"packs":["lidza/db","lidza/llm"]}`), 0o644)
	os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module app\n\ngo 1.27\n\nrequire (\n\tgithub.com/agim/lidza v0.0.0\n\tgithub.com/jackc/pgx/v5 v5.11.0\n\tgithub.com/shopspring/decimal v1.4.0\n\tgithub.com/google/uuid v1.6.0 // indirect\n)\n\nreplace github.com/agim/lidza => "+frameworkRoot(t)+"\n"), 0o644)
	os.WriteFile(filepath.Join(dir, "routes.go"), []byte("package main\n\nimport _ \"github.com/agim/lidza/packs/llm\"\n"), 0o644)
	os.MkdirAll(filepath.Join(dir, "docs"), 0o755)
	os.WriteFile(filepath.Join(dir, "docs", "decisions.md"), []byte("# Decisions\n\n## 2026-09-26: Packs at creation: db, auth\n\nWhy: the shape.\n"), 0o644)
	var got []string
	for _, d := range Rules(context.Background(), dir) {
		if d.Code == "L012" {
			got = append(got, strings.Fields(d.Message)[1])
		}
	}
	// db is named; llm is not; pgx is the framework's own; decimal is the app's.
	if strings.Join(got, ",") != "llm,github.com/shopspring/decimal" {
		t.Fatalf("L012: %v", got)
	}
	os.WriteFile(filepath.Join(dir, "docs", "decisions.md"), []byte("# Decisions\n\n## 2026-09-26: Packs at creation: db, llm\n\nWhy: the shape.\n\n## 2026-09-26: Money as decimal\n\nWhy: shopspring/decimal for exact amounts.\n"), 0o644)
	for _, d := range Rules(context.Background(), dir) {
		if d.Code == "L012" {
			t.Fatalf("still flagged: %s", d.Message)
		}
	}
}
