package diag

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// L010: each shape, with a near miss that must stay silent.
// Key-shaped test values, built at run time so the source holds nothing
// a secret scanner (L010 itself, or the code host's) takes for a key.
var (
	fakeSecretKey         = "sk_" + "live_4eC39HqLyjWDarjtT1zdp7dc0123"
	fakeTestKey           = "sk_" + "test_4eC39HqLyjWDarjtT1zdp7dc0123"
	fakeRestrictedKey     = "rk_" + "live_51H8abcdefghijklmnopqrstuv"
	fakeRestrictedTestKey = "rk_" + "test_51H8abcdefghijklmnopqrstuv"
	fakeWebhookSecret     = "whsec_" + "MfKQ9r8GKYqrTwjUPD8ILPZIo2LaLaSw"
)

func TestSecretShapes(t *testing.T) {
	for _, c := range []struct {
		s, kind string
	}{
		{`"` + fakeSecretKey + `"`, "a Stripe secret key"},
		{`"` + fakeTestKey + `"`, "a Stripe secret key"},
		{`"` + fakeRestrictedKey + `"`, "a Stripe secret key"},
		{`"` + fakeRestrictedTestKey + `"`, "a Stripe secret key"},
		{`"pk_live_51H8abcdefghijklmnopqrstuv"`, ""},
		{`"pk_test_51H8abcdefghijklmnopqrstuv"`, ""},
		{`"sk_test_123"`, ""},
		{`"ri` + `sk_` + `live_abcdefghijklmnopqrstuvwxyz"`, ""},
		{`"` + fakeWebhookSecret + `"`, "a Stripe webhook secret"},
		{`"whsec_"`, ""},
		{`"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.dozjgNryP4J3jVmNHl0w5N_XgL0n3I9PlFUP0THsR8U"`, "a JSON Web Token"},
		{`"eyJhbGciOiJIUzI1NiJ9"`, ""},
		{`"a.b.c"`, ""},
		{`"postgres://app:s3cr3t-Pw@db.internal:5432/app"`, "a database URL with its password"},
		{`"postgresql://app:s3cr3t@db/app?sslmode=require"`, "a database URL with its password"},
		{`"mysql://root:hunter22@tcp/app"`, "a database URL with its password"},
		{`"redis://:s3cr3tpw@cache:6379/0"`, "a database URL with its password"},
		{`"rediss://default:s3cr3tpw@cache:6380"`, "a database URL with its password"},
		{`"postgres://127.0.0.1:5432/app"`, ""},
		{`"postgres:///app_dev?host=/var/run/postgresql"`, ""},
		{`"redis://127.0.0.1:6379"`, ""},
		{`"postgres://user:password@host/db"`, ""},
		{`"postgres://%s:%s@%s/%s"`, ""},
		{"`postgres://${user}:${pass}@${host}/db`", ""},
		{`"postgres://app@db/app"`, ""},
	} {
		if got := secretShape(c.s); got != c.kind {
			t.Errorf("%s: got %q, want %q", c.s, got, c.kind)
		}
	}
}

// L010 in the frontend: the same shapes on any line, the ignore comment
// honoured, generated files and node_modules skipped.
func TestWebSecrets(t *testing.T) {
	dir := t.TempDir()
	write := func(name, body string) {
		os.MkdirAll(filepath.Dir(filepath.Join(dir, name)), 0o755)
		os.WriteFile(filepath.Join(dir, name), []byte(body), 0o644)
	}
	write("src/pay.ts", `const stripe = '`+fakeSecretKey+`'
const publishable = 'pk_live_51H8abcdefghijklmnopqrstuv'
// lidza:ignore L010 (a documented sample token)
const sample = 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.dozjgNryP4J3jVmNHl0w5N_XgL0n3I9PlFUP0THsR8U'
export const db = "postgres://app:s3cr3t-Pw@db.internal/app"
`)
	write("src/Hook.svelte", "<script>\n  const hook = '"+fakeWebhookSecret+"'\n</script>\n")
	write("src/gen/client.ts", "// Code generated by lidza. DO NOT EDIT.\nconst k = '"+fakeSecretKey+"'\n")
	write("src/node_modules/x/index.js", "const k = '"+fakeSecretKey+"'\n")
	var got []string
	for _, d := range WebRules(dir) {
		if d.Code != "L010" || d.Layer != "frontend" {
			t.Fatalf("unexpected: %+v", d)
		}
		got = append(got, d.File+":"+itoa(d.Line)+":"+itoa(d.Column))
	}
	if want := "src/Hook.svelte:2:17,src/pay.ts:1:17,src/pay.ts:5:20"; strings.Join(got, ",") != want {
		t.Fatalf("got %v\nwant %s", got, want)
	}
}

func writeModule(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	files["go.mod"] = "module app\n\ngo 1.27\n"
	for name, body := range files {
		os.MkdirAll(filepath.Dir(filepath.Join(dir, name)), 0o755)
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

func findings(root, code string) []string {
	var out []string
	for _, d := range Rules(context.Background(), root) {
		if d.Code == code {
			out = append(out, d.File+":"+itoa(d.Line)+" "+d.Message)
		}
	}
	return out
}

// L016: a dropped error is flagged; the calls that cannot fail, deferred
// calls, a Close before a return and ignored lines are not.
func TestDiscardedErrors(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"main.go": `package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"
)

func main() {}

func drops(w io.Writer, s string, data []byte) error {
	os.Remove("x")
	var v map[string]any
	_ = json.Unmarshal(data, &v)
	n, _ := strconv.Atoi(s)
	fmt.Fprintf(w, "%d", n)
	check := func() error { return nil }
	check()
	return nil
}

func fine(s string) error {
	fmt.Println("x")
	fmt.Printf("%s\n", s)
	fmt.Fprintf(os.Stderr, "%s\n", s)
	var b bytes.Buffer
	b.WriteString(s)
	fmt.Fprintf(&b, "%s", s)
	var sb strings.Builder
	sb.WriteString(s)
	h := sha256.New()
	h.Write([]byte(s))
	fmt.Fprint(h, s)
	f, err := os.Open(s)
	if err != nil {
		return err
	}
	defer f.Close()
	g, err := os.Open(s)
	if err != nil {
		return err
	}
	if _, err := g.Seek(0, 0); err != nil {
		g.Close()
		return err
	}
	// lidza:ignore L016 (best effort)
	os.Remove(s)
	n, err := strconv.Atoi(s)
	_ = n
	return err
}
`,
		"main_test.go": "package main\n\nimport \"os\"\n\nfunc helper() { os.Remove(\"x\") }\n",
		"gen.go":       "// Code generated by x. DO NOT EDIT.\n\npackage main\n\nimport \"os\"\n\nfunc generated() { os.Remove(\"x\") }\n",
	})
	got := findings(dir, "L016")
	want := []string{
		"main.go:17 the error from os.Remove is dropped",
		"main.go:19 the error from json.Unmarshal is dropped",
		"main.go:20 the error from strconv.Atoi is dropped",
		"main.go:21 the error from fmt.Fprintf is dropped",
		"main.go:23 the error from check is dropped",
	}
	if len(got) != len(want) {
		t.Fatalf("got %d:\n%s", len(got), strings.Join(got, "\n"))
	}
	for i := range want {
		if !strings.HasPrefix(got[i], want[i]) {
			t.Errorf("got %s\nwant %s", got[i], want[i])
		}
	}
}

// L017: a copied function body, renamed, is flagged at the copy with the
// first's place; a table of like cases, code of the same shape calling
// other functions, generated files and ignored copies are not.
func TestDuplicates(t *testing.T) {
	body := func(name, v, lit string) string {
		return `func ` + name + `(items []string) (int, error) {
	total := 0
	for _, ` + v + ` := range items {
		if ` + v + ` == "` + lit + `" {
			continue
		}
		n, err := strconv.Atoi(` + v + `)
		if err != nil {
			return 0, fmt.Errorf("` + lit + `: %w", err)
		}
		if n < 0 {
			return 0, errors.New("` + lit + ` negative")
		}
		total += n
	}
	if total > 100 {
		total = 100
	}
	return total, nil
}
`
	}
	imports := "import (\n\t\"errors\"\n\t\"fmt\"\n\t\"strconv\"\n)\n\n"
	dir := writeModule(t, map[string]string{
		"a.go": "package main\n\n" + imports + "func main() {}\n\n" + body("sumPosts", "p", "post"),
		"b.go": "package main\n\n" + imports + body("sumTags", "tag", "tag") + "\n" +
			// Same shape, other calls: not a copy.
			strings.ReplaceAll(strings.ReplaceAll(body("sumProducts", "p", "product"), "strconv.Atoi", "parseQty"), "errors.New", "fmt.Errorf") +
			"\nfunc parseQty(s string) (int, error) { return len(s), nil }\n",
		"c.go":   "package main\n\n" + imports + "// lidza:ignore L017 (kept apart on purpose)\n" + body("sumCategories", "c", "category"),
		"gen.go": "// Code generated by x. DO NOT EDIT.\n\npackage main\n\n" + imports + body("sumGenerated", "g", "gen"),
		"table.go": `package main

func kind(s string) map[string]any {
	var t map[string]any
	switch s {
	case "uuid":
		t = map[string]any{"type": "string", "format": "uuid"}
	case "time":
		t = map[string]any{"type": "string", "format": "date-time"}
	case "date":
		t = map[string]any{"type": "string", "format": "date"}
	case "int":
		t = map[string]any{"type": "integer", "format": "int32"}
	case "bigint":
		t = map[string]any{"type": "integer", "format": "int64"}
	case "float":
		t = map[string]any{"type": "number", "format": "double"}
	case "bytes":
		t = map[string]any{"type": "string", "format": "byte"}
	case "bool":
		t = map[string]any{"type": "boolean", "format": "bool"}
	case "uri":
		t = map[string]any{"type": "string", "format": "uri"}
	}
	return t
}
`,
	})
	got := findings(dir, "L017")
	if len(got) != 1 || !strings.HasPrefix(got[0], "b.go:10 these ") || !strings.Contains(got[0], "repeat a.go:12 ") || !strings.Contains(got[0], "extract a function") {
		t.Fatalf("L017: %v", got)
	}
}
