package diag

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRules(t *testing.T) {
	dir := t.TempDir()
	write := func(name, body string) {
		os.MkdirAll(filepath.Dir(filepath.Join(dir, name)), 0o755)
		os.WriteFile(filepath.Join(dir, name), []byte(body), 0o644)
	}
	write("app.go", `package main

import (
	"context"
	"net/http"

	"github.com/agim/lidza/pkg/router"
)

var sessions = map[string]int{}
var cache = make(map[string][]byte)
var recent []string
var limit = 10
var mu sync.Mutex

func raw(w http.ResponseWriter, r *http.Request) {
	go func() {}()
}

func typed(ctx context.Context, req *router.Request[router.None]) (int, error) {
	go work()
	return 0, nil
}

func work() { go func() {}() }
`)
	write("gen.go", "// Code generated by x. DO NOT EDIT.\n\npackage main\n\nvar generated = map[string]int{}\n")
	write("app_test.go", "package main\n\nvar inTest = map[string]int{}\n")
	write("node_modules/x/x.go", "package x\n\nvar ignored = map[string]int{}\n")

	got := Rules(dir)
	var lines []string
	for _, d := range got {
		lines = append(lines, d.Code+" "+d.File+":"+itoa(d.Line))
	}
	want := "L001 app.go:10,L001 app.go:11,L001 app.go:12,L002 app.go:17,L002 app.go:21"
	if strings.Join(lines, ",") != want {
		t.Fatalf("got %v\nwant %s", lines, want)
	}
	for _, d := range got {
		if d.Severity != "warning" || d.Layer != "go" {
			t.Fatalf("severity: %+v", d)
		}
	}
}

func itoa(n int) string {
	return strings.TrimSpace(strings.Repeat(" ", 0) + string(rune('0'+n/10)) + string(rune('0'+n%10)))
}
