// Package crud generates a resource from a schema.lidza model: the sqlc
// queries, the Create and Update types, a handlers file with the five
// typed routes, and the registration line in routes.go. The output is
// ordinary app code, generated once and edited freely.
package crud

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/agim/lidza/pkg/pack"
	"github.com/agim/lidza/pkg/schema"
)

// Options for Generate.
type Options struct {
	// Model is the model name in schema.lidza.
	Model string
	// Module is the app's Go module path.
	Module string
	// Force overwrites an existing handlers file.
	Force bool
}

// Result lists what was written.
type Result struct {
	Files      []string
	RoutesLine string
	Registered bool
}

// Generate writes the resource into root.
func Generate(root string, opt Options) (*Result, error) {
	s, err := schema.Load(root)
	if err != nil {
		return nil, err
	}
	if s == nil {
		return nil, errors.New("no schema.lidza")
	}
	m := s.Model(opt.Model)
	if m == nil || !m.Persisted {
		return nil, fmt.Errorf("schema.lidza has no model %s (types are not resources)", opt.Model)
	}
	if _, err := os.Stat(filepath.Join(root, pack.SQLCFile)); err != nil {
		return nil, errors.New("the resource generator needs the db pack: run `lidza pack add db` first")
	}
	r := &Resource{Schema: s, Model: m, Module: opt.Module}
	if err := r.check(); err != nil {
		return nil, err
	}
	res := &Result{}
	write := func(rel, content string, overwrite bool) error {
		p := filepath.Join(root, rel)
		if _, err := os.Stat(p); err == nil && !overwrite {
			return fmt.Errorf("%s exists; pass --force to overwrite", rel)
		}
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			return err
		}
		res.Files = append(res.Files, rel)
		return os.WriteFile(p, []byte(content), 0o644)
	}
	if err := write(filepath.Join(pack.QueriesDir, m.Table+".sql"), r.SQL(), true); err != nil {
		return nil, err
	}
	if err := write(filepath.Join("handlers", m.Table+".go"), r.Handlers(), opt.Force); err != nil {
		return nil, err
	}
	if _, err := os.Stat(filepath.Join(root, "handlers", "convert.go")); err != nil {
		if err := write(filepath.Join("handlers", "convert.go"), convertHelpers, true); err != nil {
			return nil, err
		}
	}
	added, err := appendTypes(root, s, r)
	if err != nil {
		return nil, err
	}
	if added {
		res.Files = append(res.Files, schema.FileName)
	}
	res.RoutesLine = "handlers." + m.Name + "Routes(r)"
	registered, err := registerRoutes(root, opt.Module, res.RoutesLine)
	if err != nil {
		return nil, err
	}
	res.Registered = registered
	if registered {
		res.Files = append(res.Files, "routes.go")
	}
	return res, nil
}

// Resource is one model with the derived names.
type Resource struct {
	Schema *schema.Schema
	Model  *schema.Model
	Module string
}

// Names.
func (r *Resource) Name() string   { return r.Model.Name }
func (r *Resource) Plural() string { return plural(r.Model.Name) }
func (r *Resource) Path() string   { return "/api/v1/" + strings.ToLower(plural(r.Model.Name)) }

// check rejects models the generator cannot map.
func (r *Resource) check() error {
	id := r.Model.IDField()
	if id.Type != "uuid" && id.Type != "string" && id.Type != "int" && id.Type != "bigint" {
		return fmt.Errorf("model %s: id must be uuid, string, int or bigint", r.Model.Name)
	}
	for _, f := range r.Model.Fields {
		if f.Array {
			switch f.Type {
			case "string", "text", "uuid", "int", "bigint", "float", "bool":
			default:
				return fmt.Errorf("model %s: %s: arrays of %s are not supported by the resource generator; write that handler by hand", r.Model.Name, f.Name, f.Type)
			}
		}
	}
	return nil
}

// creatable fields: everything but the id and timestamps the database
// fills.
func (r *Resource) creatable() []*schema.Field {
	var out []*schema.Field
	for _, f := range r.Model.Fields {
		if f.ID || ((f.Type == "time" || f.Type == "date") && f.Default == "now()") {
			continue
		}
		out = append(out, f)
	}
	return out
}

func (r *Resource) orderBy() string {
	for _, f := range r.Model.Fields {
		if f.Name == "createdAt" {
			return "created_at DESC"
		}
	}
	return col(r.Model.IDField())
}

// SQL renders db/queries/<table>.sql.
func (r *Resource) SQL() string {
	t := qid(r.Model.Table)
	id := r.Model.IDField()
	var b strings.Builder
	fmt.Fprintf(&b, "-- Queries for %s, generated by lidza gen resource. Edit freely; regenerate to reset.\n\n", r.Model.Name)
	fmt.Fprintf(&b, "-- name: List%s :many\nSELECT * FROM %s ORDER BY %s LIMIT $1 OFFSET $2;\n\n", r.Plural(), t, r.orderBy())
	fmt.Fprintf(&b, "-- name: Count%s :one\nSELECT count(*) FROM %s;\n\n", r.Plural(), t)
	fmt.Fprintf(&b, "-- name: Get%s :one\nSELECT * FROM %s WHERE %s = $1;\n\n", r.Name(), t, col(id))
	var cols, vals []string
	for i, f := range r.creatable() {
		cols = append(cols, col(f))
		vals = append(vals, fmt.Sprintf("$%d", i+1))
	}
	fmt.Fprintf(&b, "-- name: Create%s :one\nINSERT INTO %s (%s) VALUES (%s) RETURNING *;\n\n", r.Name(), t, strings.Join(cols, ", "), strings.Join(vals, ", "))
	var sets []string
	for _, f := range r.creatable() {
		sets = append(sets, fmt.Sprintf("%s = COALESCE(sqlc.narg('%s'), %s)", col(f), snake(f.Name), col(f)))
	}
	fmt.Fprintf(&b, "-- name: Update%s :one\nUPDATE %s SET %s WHERE %s = sqlc.arg('%s') RETURNING *;\n\n", r.Name(), t, strings.Join(sets, ", "), col(id), snake(id.Name))
	fmt.Fprintf(&b, "-- name: Delete%s :execrows\nDELETE FROM %s WHERE %s = $1;\n", r.Name(), t, col(id))
	return b.String()
}

// Handlers renders handlers/<table>.go.
func (r *Resource) Handlers() string {
	name, plural := r.Name(), r.Plural()
	lower := lowerFirst(name)
	lowerPlural := lowerFirst(plural)
	id := r.Model.IDField()
	var b strings.Builder
	fmt.Fprintf(&b, "// Generated once by lidza gen resource %s; edit freely.\n\npackage handlers\n\n", name)
	b.WriteString("import (\n\t\"context\"\n\t\"errors\"\n\t\"net/http\"\n")
	if r.usesJSON() {
		b.WriteString("\t\"encoding/json\"\n")
	}
	if id.Type == "int" || id.Type == "bigint" {
		b.WriteString("\t\"strconv\"\n")
	}
	b.WriteString("\n\t\"github.com/jackc/pgx/v5\"\n\n\t\"github.com/agim/lidza/packs/db\"\n\t\"github.com/agim/lidza/pkg/router\"\n\n")
	fmt.Fprintf(&b, "\t\"%s/db/queries/gen\"\n\t\"%s/schema\"\n)\n\n", r.Module, r.Module)

	fmt.Fprintf(&b, "// %sRoutes registers the %s resource under %s.\nfunc %sRoutes(r *router.Router) {\n", name, name, r.Path(), name)
	fmt.Fprintf(&b, "\trouter.Route(r, \"GET %s\", list%s)\n", r.Path(), plural)
	fmt.Fprintf(&b, "\trouter.Route(r, \"GET %s/{id}\", get%s)\n", r.Path(), name)
	fmt.Fprintf(&b, "\trouter.Route(r, \"POST %s\", create%s)\n", r.Path(), name)
	fmt.Fprintf(&b, "\trouter.Route(r, \"PATCH %s/{id}\", update%s)\n", r.Path(), name)
	fmt.Fprintf(&b, "\trouter.Route(r, \"DELETE %s/{id}\", delete%s)\n}\n\n", r.Path(), name)

	// id parsing
	idParse := "id := req.Param(\"id\")\n"
	idType := "string"
	if id.Type == "int" {
		idType = "int32"
		idParse = "id64, err := strconv.ParseInt(req.Param(\"id\"), 10, 32)\n\tif err != nil {\n\t\treturn out, router.Errorf(http.StatusBadRequest, \"id must be a number\")\n\t}\n\tid := int32(id64)\n"
	} else if id.Type == "bigint" {
		idType = "int64"
		idParse = "id, err := strconv.ParseInt(req.Param(\"id\"), 10, 64)\n\tif err != nil {\n\t\treturn out, router.Errorf(http.StatusBadRequest, \"id must be a number\")\n\t}\n"
	}
	_ = idType

	fmt.Fprintf(&b, "func list%s(ctx context.Context, req *router.Request[router.None]) (schema.%sList, error) {\n", plural, name)
	fmt.Fprintf(&b, "\tlimit, offset := PageParams(req, 50, 200)\n\tq := queries.New(db.From(ctx))\n\trows, err := q.List%s(ctx, queries.List%sParams{Limit: limit, Offset: offset})\n\tif err != nil {\n\t\treturn schema.%sList{}, err\n\t}\n", plural, plural, name)
	fmt.Fprintf(&b, "\ttotal, err := q.Count%s(ctx)\n\tif err != nil {\n\t\treturn schema.%sList{}, err\n\t}\n", plural, name)
	fmt.Fprintf(&b, "\titems := make([]schema.%s, len(rows))\n\tfor i, row := range rows {\n\t\titems[i] = to%s(row)\n\t}\n\treturn schema.%sList{Items: items, Total: int(total)}, nil\n}\n\n", name, name, name)

	fmt.Fprintf(&b, "func get%s(ctx context.Context, req *router.Request[router.None]) (schema.%s, error) {\n\tvar out schema.%s\n\t%s", name, name, name, idParse)
	fmt.Fprintf(&b, "\trow, err := queries.New(db.From(ctx)).Get%s(ctx, id)\n\tif errors.Is(err, pgx.ErrNoRows) {\n\t\treturn out, router.NotFound(\"%s\")\n\t}\n\tif err != nil {\n\t\treturn out, err\n\t}\n\treturn to%s(row), nil\n}\n\n", name, lower, name)

	fmt.Fprintf(&b, "func create%s(ctx context.Context, req *router.Request[schema.Create%s]) (schema.%s, error) {\n\tin := req.Body\n\trow, err := queries.New(db.From(ctx)).Create%s(ctx, queries.Create%sParams{\n", name, name, name, name, name)
	for _, f := range r.creatable() {
		fmt.Fprintf(&b, "\t\t%s: %s,\n", sqlcName(f), r.toParam(f, "in."+exported(f.Name), false))
	}
	fmt.Fprintf(&b, "\t})\n\tif err != nil {\n\t\treturn schema.%s{}, err\n\t}\n\treq.Status(http.StatusCreated)\n\treturn to%s(row), nil\n}\n\n", name, name)

	fmt.Fprintf(&b, "func update%s(ctx context.Context, req *router.Request[schema.Update%s]) (schema.%s, error) {\n\tvar out schema.%s\n\t%s\tin := req.Body\n\trow, err := queries.New(db.From(ctx)).Update%s(ctx, queries.Update%sParams{\n\t\t%s: id,\n", name, name, name, name, idParse, name, name, sqlcName(id))
	for _, f := range r.creatable() {
		fmt.Fprintf(&b, "\t\t%s: %s,\n", sqlcName(f), r.toParam(f, "in."+exported(f.Name), true))
	}
	fmt.Fprintf(&b, "\t})\n\tif errors.Is(err, pgx.ErrNoRows) {\n\t\treturn out, router.NotFound(\"%s\")\n\t}\n\tif err != nil {\n\t\treturn out, err\n\t}\n\treturn to%s(row), nil\n}\n\n", lower, name)

	fmt.Fprintf(&b, "func delete%s(ctx context.Context, req *router.Request[router.None]) (router.None, error) {\n\tvar out router.None\n\t%s", name, idParse)
	fmt.Fprintf(&b, "\tn, err := queries.New(db.From(ctx)).Delete%s(ctx, id)\n\tif err != nil {\n\t\treturn out, err\n\t}\n\tif n == 0 {\n\t\treturn out, router.NotFound(\"%s\")\n\t}\n\treturn out, nil\n}\n\n", name, lower)

	fmt.Fprintf(&b, "// to%s maps a row to the API type.\nfunc to%s(row queries.%s) schema.%s {\n\treturn schema.%s{\n", name, name, name, name, name)
	for _, f := range r.Model.Fields {
		fmt.Fprintf(&b, "\t\t%s: %s,\n", exported(f.Name), r.fromRow(f, "row."+sqlcName(f)))
	}
	b.WriteString("\t}\n}\n")
	_ = lowerPlural
	return b.String()
}

func (r *Resource) usesJSON() bool {
	for _, f := range r.Model.Fields {
		if f.Type == "json" {
			return true
		}
	}
	return false
}

// fromRow renders the expression converting a sqlc row field to the
// schema type.
func (r *Resource) fromRow(f *schema.Field, expr string) string {
	isEnum := r.Schema.Enum(f.Type) != nil
	switch {
	case f.Array && f.Type == "int":
		return "IntsFrom(" + expr + ")"
	case f.Array:
		return expr
	case f.Type == "int" && f.Optional:
		return "PtrInt(" + expr + ")"
	case f.Type == "int":
		return "int(" + expr + ")"
	case f.Type == "json":
		return "json.RawMessage(" + expr + ")"
	case isEnum && f.Optional:
		return fmt.Sprintf("(*schema.%s)(%s)", f.Type, expr)
	case isEnum:
		return fmt.Sprintf("schema.%s(%s)", f.Type, expr)
	}
	return expr
}

// toParam renders the expression converting a schema value to the sqlc
// parameter type; forUpdate treats every field as optional (narg).
func (r *Resource) toParam(f *schema.Field, expr string, forUpdate bool) string {
	isEnum := r.Schema.Enum(f.Type) != nil
	optional := f.Optional || forUpdate
	switch {
	case f.Array && f.Type == "int":
		return "Int32sFrom(" + expr + ")"
	case f.Array:
		return expr
	case f.Type == "int" && optional:
		return "PtrInt32(" + expr + ")"
	case f.Type == "int":
		return "int32(" + expr + ")"
	case f.Type == "json":
		return "[]byte(" + expr + ")"
	case isEnum && optional:
		return fmt.Sprintf("(*queries.%s)(%s)", f.Type, expr)
	case isEnum:
		return fmt.Sprintf("queries.%s(%s)", f.Type, expr)
	case forUpdate && !f.Optional && !f.Array && f.Type != "bytes":
		// Update types make every field optional (pointer); sqlc nargs take
		// pointers too.
		return expr
	}
	return expr
}

const convertHelpers = `// Generated once by lidza gen resource; helpers shared by the resources.

package handlers

import (
	"strconv"

	"github.com/agim/lidza/pkg/router"
)

// PageParams reads limit and offset from the query with a default and a
// cap on the limit.
func pageParams[In any](req *router.Request[In], def, max int) (limit, offset int32) {
	limit = int32(def)
	if v, err := strconv.Atoi(req.Query("limit")); err == nil && v > 0 {
		limit = int32(min(v, max))
	}
	if v, err := strconv.Atoi(req.Query("offset")); err == nil && v >= 0 {
		offset = int32(v)
	}
	return limit, offset
}

// PtrInt converts a nullable int32 column to the schema's *int.
func PtrInt(p *int32) *int {
	if p == nil {
		return nil
	}
	v := int(*p)
	return &v
}

// PtrInt32 converts the schema's *int to a nullable int32 parameter.
func PtrInt32(p *int) *int32 {
	if p == nil {
		return nil
	}
	v := int32(*p)
	return &v
}

// IntsFrom converts an integer[] column.
func IntsFrom(in []int32) []int {
	out := make([]int, len(in))
	for i, v := range in {
		out[i] = int(v)
	}
	return out
}

// Int32sFrom converts to an integer[] parameter.
func Int32sFrom(in []int) []int32 {
	out := make([]int32, len(in))
	for i, v := range in {
		out[i] = int32(v)
	}
	return out
}
`

// appendTypes adds Create<Model>, Update<Model> and <Model>List to
// schema.lidza when missing.
func appendTypes(root string, s *schema.Schema, r *Resource) (bool, error) {
	var b strings.Builder
	name := r.Name()
	if s.Model("Create"+name) == nil {
		fmt.Fprintf(&b, "\n// Body of POST %s.\ntype Create%s {\n", r.Path(), name)
		for _, f := range r.creatable() {
			b.WriteString("  " + fieldLine(f, false) + "\n")
		}
		b.WriteString("}\n")
	}
	if s.Model("Update"+name) == nil {
		fmt.Fprintf(&b, "\n// Body of PATCH %s/{id}: every field optional, absent fields keep their value.\ntype Update%s {\n", r.Path(), name)
		for _, f := range r.creatable() {
			b.WriteString("  " + fieldLine(f, true) + "\n")
		}
		b.WriteString("}\n")
	}
	if s.Model(name+"List") == nil {
		fmt.Fprintf(&b, "\n// Reply of GET %s.\ntype %sList {\n  items %s[]\n  total int\n}\n", r.Path(), name, name)
	}
	if b.Len() == 0 {
		return false, nil
	}
	f, err := os.OpenFile(filepath.Join(root, schema.FileName), os.O_APPEND|os.O_WRONLY, 0o644)
	if err != nil {
		return false, err
	}
	defer f.Close()
	_, err = f.WriteString(b.String())
	return true, err
}

// fieldLine renders a field for a type block, keeping its validation
// rules and, for updates, making it optional.
func fieldLine(f *schema.Field, optional bool) string {
	t := f.Type
	if f.Array {
		t += "[]"
	}
	if f.Optional || optional {
		t += "?"
	}
	parts := []string{f.Name, t}
	if f.Min != nil {
		parts = append(parts, "@min("+fnum(*f.Min)+")")
	}
	if f.Max != nil {
		parts = append(parts, "@max("+fnum(*f.Max)+")")
	}
	if f.Email {
		parts = append(parts, "@email")
	}
	if f.URL {
		parts = append(parts, "@url")
	}
	if f.Pattern != "" {
		parts = append(parts, fmt.Sprintf("@pattern(%q)", f.Pattern))
	}
	return strings.Join(parts, " ")
}

// registerRoutes adds handlers.<Model>Routes(r) to routes.go and the
// handlers import, unless present. It reports false when routes.go does
// not have the expected shape, so the caller prints the line to add.
func registerRoutes(root, module, line string) (bool, error) {
	p := filepath.Join(root, "routes.go")
	data, err := os.ReadFile(p)
	if err != nil {
		return false, nil
	}
	src := string(data)
	if strings.Contains(src, line) {
		return true, nil
	}
	marker := "func routes(r *router.Router) {\n"
	if !strings.Contains(src, marker) {
		return false, nil
	}
	src = strings.Replace(src, marker, marker+"\t"+line+"\n", 1)
	imp := fmt.Sprintf("\t%q\n", module+"/handlers")
	if !strings.Contains(src, imp) {
		if i := strings.Index(src, "import (\n"); i >= 0 {
			src = src[:i+len("import (\n")] + imp + src[i+len("import (\n"):]
		} else {
			return false, nil
		}
	}
	return true, os.WriteFile(p, []byte(src), 0o644)
}

// Naming helpers, matching pkg/schema for the schema side and sqlc for
// the query side.

func snake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('_')
			}
			b.WriteRune(r + 'a' - 'A')
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

var initialisms = map[string]bool{"id": true, "url": true, "api": true, "http": true, "json": true, "uuid": true, "sql": true, "ip": true, "html": true}

func exported(s string) string {
	var b strings.Builder
	for _, p := range strings.Split(snake(s), "_") {
		if p == "" {
			continue
		}
		if initialisms[p] {
			b.WriteString(strings.ToUpper(p))
		} else {
			b.WriteString(strings.ToUpper(p[:1]) + p[1:])
		}
	}
	return b.String()
}

// sqlcName is sqlc's struct field for a column: each part title-cased,
// "id" as "ID".
func sqlcName(f *schema.Field) string {
	var b strings.Builder
	for _, p := range strings.Split(snake(f.Name), "_") {
		if p == "" {
			continue
		}
		if p == "id" {
			b.WriteString("ID")
		} else {
			b.WriteString(strings.ToUpper(p[:1]) + p[1:])
		}
	}
	return b.String()
}

var reserved = map[string]bool{"user": true, "order": true, "group": true, "table": true, "select": true, "from": true, "where": true, "limit": true, "offset": true, "default": true, "check": true, "primary": true, "references": true, "to": true, "in": true, "on": true, "or": true, "and": true, "not": true, "null": true, "with": true, "all": true, "any": true, "as": true, "asc": true, "desc": true, "column": true, "constraint": true, "create": true, "distinct": true, "do": true, "else": true, "end": true, "grant": true, "having": true, "into": true, "only": true, "then": true, "union": true, "unique": true, "using": true, "when": true}

func qid(name string) string {
	if reserved[name] {
		return `"` + name + `"`
	}
	return name
}

func col(f *schema.Field) string { return qid(snake(f.Name)) }

func plural(name string) string {
	switch {
	case strings.HasSuffix(name, "s"), strings.HasSuffix(name, "x"), strings.HasSuffix(name, "ch"), strings.HasSuffix(name, "sh"):
		return name + "es"
	case strings.HasSuffix(name, "y") && len(name) > 1 && !strings.ContainsRune("aeiou", rune(name[len(name)-2])):
		return name[:len(name)-1] + "ies"
	}
	return name + "s"
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func fnum(v float64) string {
	s := strings.TrimRight(strings.TrimRight(fmt.Sprintf("%.6f", v), "0"), ".")
	return s
}
