package sdk

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/agim/lidza/pkg/inspect"
)

// Dart renders the Dart client package (`lidza_client`, on package:http):
// types as classes with fromJson and toJson, enums with their wire
// values, and one method per operation on LidzaClient. Files are keyed by
// path inside the package directory.
func Dart(c *inspect.Context) map[string]string {
	return map[string]string{
		"pubspec.yaml":          dartPubspec(c),
		"lib/lidza_client.dart": "// Code generated by lidza. DO NOT EDIT.\n\nlibrary lidza_client;\n\nexport 'src/types.dart';\nexport 'src/client.dart';\n",
		"lib/src/types.dart":    dartTypes(c),
		"lib/src/client.dart":   dartClient(c),
		"analysis_options.yaml": "include: package:lints/recommended.yaml\n",
	}
}

// WriteDart writes the package into dir (relative to root), touching only
// files whose content changed.
func WriteDart(root, dir string, c *inspect.Context) error {
	for name, content := range Dart(c) {
		p := filepath.Join(root, dir, name)
		if old, err := os.ReadFile(p); err == nil && string(old) == content {
			continue
		}
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func dartPubspec(c *inspect.Context) string {
	name := "lidza_client"
	return fmt.Sprintf(`# Code generated by lidza for %s. DO NOT EDIT.
name: %s
description: Typed client for the %s API, generated from the Go handlers.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  http: ^1.2.0

dev_dependencies:
  lints: ^5.0.0
`, c.App.Name, name, c.App.Name)
}

func dartTypes(c *inspect.Context) string {
	var b strings.Builder
	b.WriteString("// Code generated by lidza from the Go handler types. DO NOT EDIT.\n\n")
	names := make([]string, 0, len(c.Schemas))
	for name := range c.Schemas {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		def, _ := c.Schemas[name].(map[string]any)
		if values := enumOf(def, c.Schemas); len(values) > 0 && def["$ref"] == nil {
			writeDartEnum(&b, name, values)
			continue
		}
		if def["type"] == "object" && def["properties"] != nil {
			writeDartClass(&b, name, def, c.Schemas)
		}
	}
	b.WriteString(`/// Field errors from a 422 reply.
class ValidationError {
  const ValidationError({required this.field, required this.rule, required this.message});

  final String field;
  final String rule;
  final String message;

  factory ValidationError.fromJson(Map<String, dynamic> json) => ValidationError(
        field: json['field'] as String,
        rule: json['rule'] as String,
        message: json['message'] as String,
      );
}
`)
	return b.String()
}

func writeDartEnum(b *strings.Builder, name string, values []string) {
	fmt.Fprintf(b, "enum %s {\n", name)
	for i, v := range values {
		sep := ","
		if i == len(values)-1 {
			sep = ";"
		}
		fmt.Fprintf(b, "  %s('%s')%s\n", dartEnumIdent(v), v, sep)
	}
	fmt.Fprintf(b, "\n  const %s(this.wire);\n\n  /// The value as the API sends it.\n  final String wire;\n\n", name)
	fmt.Fprintf(b, "  static %s fromJson(String value) => values.firstWhere((e) => e.wire == value, orElse: () => throw FormatException('unknown %s: $value'));\n\n", name, name)
	b.WriteString("  String toJson() => wire;\n}\n\n")
}

func writeDartClass(b *strings.Builder, name string, def map[string]any, all map[string]any) {
	props, _ := def["properties"].(map[string]any)
	required := map[string]bool{}
	switch req := def["required"].(type) {
	case []string:
		for _, r := range req {
			required[r] = true
		}
	case []any:
		for _, r := range req {
			required[fmt.Sprint(r)] = true
		}
	}
	fields := make([]string, 0, len(props))
	for f := range props {
		fields = append(fields, f)
	}
	sort.Strings(fields)

	fmt.Fprintf(b, "class %s {\n  const %s({\n", name, name)
	for _, f := range fields {
		p, _ := props[f].(map[string]any)
		t := dartType(p, all)
		if required[f] && !t.nullable {
			fmt.Fprintf(b, "    required this.%s,\n", dartIdent(f))
		} else {
			fmt.Fprintf(b, "    this.%s,\n", dartIdent(f))
		}
	}
	b.WriteString("  });\n\n")
	for _, f := range fields {
		p, _ := props[f].(map[string]any)
		t := dartType(p, all)
		typ := t.name
		if t.nullable || !required[f] {
			typ += "?"
		}
		fmt.Fprintf(b, "  final %s %s;\n", typ, dartIdent(f))
	}
	fmt.Fprintf(b, "\n  factory %s.fromJson(Map<String, dynamic> json) => %s(\n", name, name)
	for _, f := range fields {
		p, _ := props[f].(map[string]any)
		t := dartType(p, all)
		fmt.Fprintf(b, "        %s: %s,\n", dartIdent(f), t.decode("json['"+f+"']", t.nullable || !required[f]))
	}
	b.WriteString("      );\n\n  Map<String, dynamic> toJson() => {\n")
	for _, f := range fields {
		p, _ := props[f].(map[string]any)
		t := dartType(p, all)
		fmt.Fprintf(b, "        '%s': %s,\n", f, t.encode(dartIdent(f), t.nullable || !required[f]))
	}
	b.WriteString("      };\n}\n\n")
}

// dartT describes how a JSON Schema maps to Dart and (de)serializes.
type dartT struct {
	name     string
	nullable bool
	kind     string // scalar, datetime, enum, class, list, map, any
	elem     *dartT
}

func dartType(p map[string]any, all map[string]any) dartT {
	if p == nil {
		return dartT{name: "Object", nullable: true, kind: "any"}
	}
	if ref, ok := p["$ref"].(string); ok {
		name := strings.TrimPrefix(ref, "#/components/schemas/")
		if enumOf(p, all) != nil {
			return dartT{name: name, kind: "enum"}
		}
		return dartT{name: name, kind: "class"}
	}
	if one, ok := p["oneOf"].([]any); ok {
		for _, o := range one {
			if m, ok := o.(map[string]any); ok && m["$ref"] != nil {
				t := dartType(m, all)
				t.nullable = true
				return t
			}
		}
	}
	nullable := false
	typ := ""
	switch t := p["type"].(type) {
	case string:
		typ = t
	case []any:
		for _, x := range t {
			if x == "null" {
				nullable = true
			} else {
				typ = fmt.Sprint(x)
			}
		}
	}
	switch typ {
	case "string":
		if p["format"] == "date-time" {
			return dartT{name: "DateTime", nullable: nullable, kind: "datetime"}
		}
		return dartT{name: "String", nullable: nullable, kind: "scalar"}
	case "integer":
		return dartT{name: "int", nullable: nullable, kind: "scalar"}
	case "number":
		return dartT{name: "double", nullable: nullable, kind: "scalar"}
	case "boolean":
		return dartT{name: "bool", nullable: nullable, kind: "scalar"}
	case "array":
		items, _ := p["items"].(map[string]any)
		elem := dartType(items, all)
		return dartT{name: "List<" + elem.full() + ">", nullable: nullable, kind: "list", elem: &elem}
	case "object":
		if ap, ok := p["additionalProperties"].(map[string]any); ok {
			elem := dartType(ap, all)
			return dartT{name: "Map<String, " + elem.full() + ">", nullable: nullable, kind: "map", elem: &elem}
		}
		if p["properties"] == nil {
			return dartT{name: "Map<String, dynamic>", nullable: nullable, kind: "scalar"}
		}
	}
	return dartT{name: "Object", nullable: true, kind: "any"}
}

func (t dartT) full() string {
	if t.nullable {
		return t.name + "?"
	}
	return t.name
}

// decode renders the expression reading expr (a dynamic JSON value).
func (t dartT) decode(expr string, optional bool) string {
	var conv string
	switch t.kind {
	case "scalar":
		if t.name == "double" {
			conv = "(%s as num).toDouble()"
		} else {
			conv = "%s as " + t.name
		}
	case "datetime":
		conv = "DateTime.parse(%s as String)"
	case "enum":
		conv = t.name + ".fromJson(%s as String)"
	case "class":
		conv = t.name + ".fromJson(%s as Map<String, dynamic>)"
	case "list":
		conv = "(%s as List<dynamic>).map((e) => " + t.elem.decode("e", t.elem.nullable) + ").toList()"
	case "map":
		conv = "(%s as Map<String, dynamic>).map((k, v) => MapEntry(k, " + t.elem.decode("v", t.elem.nullable) + "))"
	default:
		return expr
	}
	if optional {
		return expr + " == null ? null : " + fmt.Sprintf(conv, expr)
	}
	return fmt.Sprintf(conv, expr)
}

// encode renders the expression writing field to JSON.
func (t dartT) encode(field string, optional bool) string {
	q := ""
	if optional {
		q = "?"
	}
	switch t.kind {
	case "datetime":
		return field + q + ".toUtc().toIso8601String()"
	case "enum":
		return field + q + ".toJson()"
	case "class":
		return field + q + ".toJson()"
	case "list":
		inner := t.elem.encode("e", t.elem.nullable)
		if inner == "e" {
			return field
		}
		return field + q + ".map((e) => " + inner + ").toList()"
	case "map":
		inner := t.elem.encode("v", t.elem.nullable)
		if inner == "v" {
			return field
		}
		return field + q + ".map((k, v) => MapEntry(k, " + inner + "))"
	}
	return field
}

func dartClient(c *inspect.Context) string {
	var b strings.Builder
	b.WriteString("// Code generated by lidza from the Go handlers. DO NOT EDIT.\n\n")
	b.WriteString("import 'dart:convert';\n\nimport 'package:http/http.dart' as http;\n\nimport 'types.dart';\n\n")
	b.WriteString(`/// A non-2xx reply.
class ApiException implements Exception {
  ApiException(this.status, this.body, this.message);

  final int status;
  final Object? body;
  final String message;

  /// The field errors when the server replied 422.
  List<ValidationError>? get fields {
    final b = body;
    if (b is Map<String, dynamic> && b['error'] == 'validation' && b['fields'] is List) {
      return (b['fields'] as List<dynamic>).map((e) => ValidationError.fromJson(e as Map<String, dynamic>)).toList();
    }
    return null;
  }

  @override
  String toString() => 'ApiException($status): $message';
}

/// The API client. Pass the base URL of the Go server; headers are sent
/// with every request (an Authorization bearer, for instance).
class LidzaClient {
  LidzaClient({required this.baseUrl, http.Client? client, Map<String, String>? headers})
      : _client = client ?? http.Client(),
        _headers = headers ?? const {};

  final String baseUrl;
  final http.Client _client;
  final Map<String, String> _headers;

  void close() => _client.close();

  Future<dynamic> _send(String method, String path, {Object? body}) async {
    final request = http.Request(method, Uri.parse('$baseUrl$path'));
    request.headers.addAll({'Accept': 'application/json', ..._headers});
    // Every request that can change state is declared JSON, body or not:
    // a cookie session is only accepted with this content type.
    if (method != 'GET' && method != 'HEAD') request.headers['Content-Type'] = 'application/json';
    if (body != null) request.body = jsonEncode(body);
    final streamed = await _client.send(request);
    final response = await http.Response.fromStream(streamed);
    Object? parsed;
    if (response.body.isNotEmpty) {
      try {
        parsed = jsonDecode(response.body);
      } on FormatException {
        parsed = response.body;
      }
    }
    if (response.statusCode < 200 || response.statusCode >= 300) {
      final message = parsed is Map<String, dynamic> && parsed['error'] is String
          ? parsed['error'] as String
          : response.reasonPhrase ?? 'error';
      throw ApiException(response.statusCode, parsed, '$method $path: ${response.statusCode} $message');
    }
    return parsed;
  }

`)
	for _, op := range c.Operations {
		var params []string
		for _, p := range op.Params {
			params = append(params, "required String "+dartIdent(p))
		}
		var args []string
		if len(params) > 0 {
			args = append(args, "{"+strings.Join(params, ", ")+"}")
		}
		if op.Input != "" {
			args = append([]string{op.Input + " body"}, args...)
		}
		ret := "void"
		if op.Output != "" {
			ret = op.Output
		}
		fmt.Fprintf(&b, "  /// %s %s\n", op.Method, op.Path)
		fmt.Fprintf(&b, "  Future<%s> %s(%s) async {\n", ret, op.ID, strings.Join(args, ", "))
		body := ""
		if op.Input != "" {
			body = ", body: body.toJson()"
		}
		if op.Output == "" {
			fmt.Fprintf(&b, "    await _send('%s', %s%s);\n  }\n\n", op.Method, dartPath(op.Path), body)
			continue
		}
		fmt.Fprintf(&b, "    final json = await _send('%s', %s%s);\n    return %s.fromJson(json as Map<String, dynamic>);\n  }\n\n", op.Method, dartPath(op.Path), body, op.Output)
	}
	b.WriteString("}\n")
	return b.String()
}

// dartPath renders "/api/v1/posts/{id}" as a Dart string with encoded
// parameters.
func dartPath(path string) string {
	out := "'" + path + "'"
	for _, name := range pathParamsOf(path) {
		out = strings.ReplaceAll(out, "{"+name+"}", "${Uri.encodeComponent("+dartIdent(name)+")}")
		out = strings.ReplaceAll(out, "{"+name+"...}", "${"+dartIdent(name)+"}")
	}
	return strings.ReplaceAll(out, "{$}", "")
}

var dartReserved = map[string]bool{"class": true, "default": true, "in": true, "is": true, "new": true, "this": true, "void": true, "with": true, "for": true, "if": true, "else": true, "do": true, "var": true, "final": true, "const": true, "enum": true, "extends": true, "super": true, "return": true, "switch": true, "case": true, "break": true, "true": true, "false": true, "null": true, "static": true, "import": true, "as": true, "try": true, "catch": true, "throw": true, "while": true, "assert": true, "await": true, "async": true}

// dartIdent turns a JSON name into a Dart identifier (lowerCamel).
func dartIdent(name string) string {
	var b strings.Builder
	upper := false
	for i, r := range name {
		switch {
		case r == '_' || r == '-' || r == ' ' || r == '.':
			upper = true
		case upper:
			b.WriteRune(toUpper(r))
			upper = false
		case i == 0:
			b.WriteRune(toLower(r))
		default:
			b.WriteRune(r)
		}
	}
	s := b.String()
	if s == "" || (s[0] >= '0' && s[0] <= '9') {
		s = "v" + s
	}
	if dartReserved[s] {
		s += "_"
	}
	return s
}

func dartEnumIdent(v string) string { return dartIdent(v) }

func toUpper(r rune) rune {
	if r >= 'a' && r <= 'z' {
		return r - 'a' + 'A'
	}
	return r
}

func toLower(r rune) rune {
	if r >= 'A' && r <= 'Z' {
		return r - 'A' + 'a'
	}
	return r
}
