// Package sdk generates the client SDKs from a project's operations. The
// TypeScript client, imported as @lidza/client, is written to
// .lidza/client and regenerated whenever the Go types change.
package sdk

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/agim/lidza/pkg/inspect"
)

// ClientDir is where the TypeScript client lives, relative to the project
// root. The template aliases @lidza/client to ClientDir/index.ts.
const ClientDir = ".lidza/client"

// TypeScript renders the client as files keyed by name: types.ts (the
// component schemas as interfaces and unions), client.ts (one function
// per operation) and index.ts.
func TypeScript(c *inspect.Context) map[string]string {
	return map[string]string{
		"types.ts":      tsTypes(c),
		"client.ts":     tsClient(c),
		"validators.ts": tsValidators(c),
		"index.ts":      "// Code generated by lidza. DO NOT EDIT.\n\nexport * from './types'\nexport * from './client'\nexport * from './validators'\n",
	}
}

// WriteTypeScript writes the client into root/.lidza/client, touching only
// files whose content changed so Vite does not reload needlessly.
func WriteTypeScript(root string, c *inspect.Context) error {
	dir := filepath.Join(root, ClientDir)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	for name, content := range TypeScript(c) {
		p := filepath.Join(dir, name)
		if old, err := os.ReadFile(p); err == nil && string(old) == content {
			continue
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func tsTypes(c *inspect.Context) string {
	var b strings.Builder
	b.WriteString("// Code generated by lidza from the Go handler types. DO NOT EDIT.\n\n")
	b.WriteString("export interface ApiErrorBody {\n  error: string\n  /** Names the error for programs when the server sets one (router.ErrorCode). */\n  code?: string\n}\n\n")
	b.WriteString("export interface ValidationErrorBody {\n  error: 'validation'\n  fields: { field: string; rule: string; message: string }[]\n}\n\n")
	names := make([]string, 0, len(c.Schemas))
	for name := range c.Schemas {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		def, _ := c.Schemas[name].(map[string]any)
		if enum, ok := def["enum"].([]any); ok {
			vals := make([]string, len(enum))
			for i, v := range enum {
				vals[i] = fmt.Sprintf("%q", v)
			}
			fmt.Fprintf(&b, "export type %s = %s\n", name, strings.Join(vals, " | "))
			fmt.Fprintf(&b, "export const %sValues: readonly %s[] = [%s]\n\n", name, name, strings.Join(vals, ", "))
			continue
		}
		if enum, ok := def["enum"].([]string); ok {
			vals := make([]string, len(enum))
			for i, v := range enum {
				vals[i] = fmt.Sprintf("%q", v)
			}
			fmt.Fprintf(&b, "export type %s = %s\n", name, strings.Join(vals, " | "))
			fmt.Fprintf(&b, "export const %sValues: readonly %s[] = [%s]\n\n", name, name, strings.Join(vals, ", "))
			continue
		}
		if def["type"] == "object" && def["properties"] != nil {
			fmt.Fprintf(&b, "export interface %s %s\n\n", name, objectBody(def, 0))
			continue
		}
		fmt.Fprintf(&b, "export type %s = %s\n\n", name, tsType(def, 0))
	}
	return b.String()
}

// objectBody renders "{ a: T; b?: U }" across lines.
func objectBody(def map[string]any, depth int) string {
	props, _ := def["properties"].(map[string]any)
	required := map[string]bool{}
	switch req := def["required"].(type) {
	case []string:
		for _, r := range req {
			required[r] = true
		}
	case []any:
		for _, r := range req {
			required[fmt.Sprint(r)] = true
		}
	}
	names := make([]string, 0, len(props))
	for n := range props {
		names = append(names, n)
	}
	sort.Strings(names)
	pad := strings.Repeat("  ", depth+1)
	var b strings.Builder
	b.WriteString("{\n")
	for _, n := range names {
		opt := ""
		if !required[n] {
			opt = "?"
		}
		p := props[n].(map[string]any)
		if p["format"] == "decimal" {
			// A decimal stays a string end to end: Number() only to display.
			digits := ""
			if prec, ok := p["x-precision"]; ok {
				digits = fmt.Sprintf(" (%v digits, %v after the point)", prec, p["x-scale"])
			}
			fmt.Fprintf(&b, "%s/** Exact decimal as a string, \"12.50\"%s. */\n", pad, digits)
		}
		switch {
		case p["format"] == "date":
			fmt.Fprintf(&b, "%s/** Calendar day, \"2026-10-06\": no time zone, never shift it. */\n", pad)
		case p["x-format"] == "local-date-time":
			fmt.Fprintf(&b, "%s/** Local date and time as typed, \"2026-10-06T10:30\" (no zone): the server reads it in the visitor's zone. */\n", pad)
		case p["format"] == "date-time":
			fmt.Fprintf(&b, "%s/** Instant in UTC, \"2026-10-06T14:30:00Z\": format it in the visitor's zone (src/datetime.ts). */\n", pad)
		}
		fmt.Fprintf(&b, "%s%s%s: %s\n", pad, tsKey(n), opt, tsType(p, depth+1))
	}
	b.WriteString(strings.Repeat("  ", depth) + "}")
	return b.String()
}

func tsKey(name string) string {
	for i, r := range name {
		ok := r == '_' || r == '$' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (i > 0 && r >= '0' && r <= '9')
		if !ok {
			return fmt.Sprintf("%q", name)
		}
	}
	return name
}

// tsType renders a JSON Schema as a TypeScript type expression.
func tsType(def map[string]any, depth int) string {
	if len(def) == 0 {
		return "unknown"
	}
	if r, ok := def["$ref"].(string); ok {
		return strings.TrimPrefix(r, "#/components/schemas/")
	}
	if one, ok := def["oneOf"].([]any); ok {
		parts := make([]string, len(one))
		for i, o := range one {
			parts[i] = tsType(o.(map[string]any), depth)
		}
		return strings.Join(parts, " | ")
	}
	if enum, ok := def["enum"]; ok {
		var parts []string
		switch e := enum.(type) {
		case []any:
			for _, v := range e {
				parts = append(parts, fmt.Sprintf("%q", v))
			}
		case []string:
			for _, v := range e {
				parts = append(parts, fmt.Sprintf("%q", v))
			}
		}
		return strings.Join(parts, " | ")
	}
	if c, ok := def["const"]; ok {
		return fmt.Sprintf("%q", c)
	}
	nullable := false
	var typ string
	switch t := def["type"].(type) {
	case string:
		typ = t
	case []any:
		for _, x := range t {
			if x == "null" {
				nullable = true
			} else {
				typ = fmt.Sprint(x)
			}
		}
	}
	var out string
	switch typ {
	case "string":
		out = "string"
	case "integer", "number":
		out = "number"
	case "boolean":
		out = "boolean"
	case "null":
		return "null"
	case "array":
		items, _ := def["items"].(map[string]any)
		inner := tsType(items, depth)
		if strings.Contains(inner, " | ") {
			inner = "(" + inner + ")"
		}
		out = inner + "[]"
	case "object":
		if def["properties"] != nil {
			out = objectBody(def, depth)
		} else if ap, ok := def["additionalProperties"].(map[string]any); ok {
			out = "Record<string, " + tsType(ap, depth) + ">"
		} else {
			out = "Record<string, unknown>"
		}
	default:
		out = "unknown"
	}
	if nullable {
		out += " | null"
	}
	return out
}

func tsClient(c *inspect.Context) string {
	var b strings.Builder
	b.WriteString("// Code generated by lidza from the Go handlers. DO NOT EDIT.\n\n")
	b.WriteString("import type * as T from './types'\n\n")
	b.WriteString(`export class ApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly body: unknown,
    message: string,
  ) {
    super(message)
    this.name = 'ApiError'
  }

  /** The error's code, when the server names one ("wrong_password"). */
  get code(): string | undefined {
    return (this.body as Partial<T.ApiErrorBody> | undefined)?.code
  }

  /** The field errors when the server replied 422. */
  get fields(): T.ValidationErrorBody['fields'] | undefined {
    const body = this.body as Partial<T.ValidationErrorBody> | undefined
    return body?.error === 'validation' ? body.fields : undefined
  }
}

export interface RequestOptions {
  signal?: AbortSignal
  headers?: Record<string, string>
  /** Query string parameters; undefined and null values are left out. */
  query?: Record<string, string | number | boolean | null | undefined>
  /** A raw request body (a File, Blob, FormData, ArrayBuffer or string)
   * for a route that reads the body itself, such as an upload; sent as
   * contentType, or the File's own type, or application/octet-stream. */
  body?: BodyInit
  contentType?: string
}

/** Options of an upload operation (a router.File route): the file is the
 * body, sent as contentType or the File's own type. */
export interface UploadOptions extends Omit<RequestOptions, 'body'> {
  /** Called as the body goes out with the bytes sent and the total. The
   * request then goes through XMLHttpRequest, so this is for the browser. */
  onProgress?: (sent: number, total: number) => void
}

let baseUrl = ''
let defaultHeaders: Record<string, string> = {}

/** Set a base URL when the API is not on the page's origin, and headers
 * sent with every request (the server renderer forwards the visitor's). */
export function configure(options: { baseUrl?: string; headers?: Record<string, string> }): void {
  if (options.baseUrl !== undefined) baseUrl = options.baseUrl.replace(/\/$/, '')
  if (options.headers !== undefined) defaultHeaders = { ...options.headers }
}

`)
	// Only what the operations use: the template compiles with
	// noUnusedLocals.
	streams, calls, uploads := 0, 0, 0
	for _, op := range c.Operations {
		switch {
		case op.Stream:
			streams++
		case op.Upload:
			uploads++
		default:
			calls++
		}
	}
	if streams+calls+uploads > 0 {
		b.WriteString(tsHelpers)
	}
	if calls > 0 {
		b.WriteString(tsRequest)
	}
	if streams > 0 {
		b.WriteString(tsStream)
	}
	if uploads > 0 {
		b.WriteString(tsUpload)
	}
	if usesEncodedParam(c.Operations) {
		b.WriteString("const p = encodeURIComponent\n\n")
	}
	b.WriteString("export const api = {\n")
	for _, op := range c.Operations {
		var args []string
		if len(op.Params) > 0 {
			fields := make([]string, len(op.Params))
			for i, name := range op.Params {
				fields[i] = tsKey(name) + ": string"
			}
			args = append(args, "params: { "+strings.Join(fields, "; ")+" }")
		}
		ret := "void"
		if op.Output != "" {
			ret = "T." + op.Output
		}
		if op.Upload {
			args = append(args, "file: Blob", "options?: UploadOptions")
			fmt.Fprintf(&b, "  /** %s %s: uploads file as the raw body; options.onProgress reports the bytes sent. */\n", op.Method, op.Path)
			fmt.Fprintf(&b, "  %s(%s): Promise<%s> {\n", op.ID, strings.Join(args, ", "), ret)
			fmt.Fprintf(&b, "    return upload<%s>(%q, %s, file, options)\n  },\n", ret, op.Method, tsPath(op.Path))
			continue
		}
		bodyArg := "undefined"
		if op.Input != "" {
			args = append(args, "body: T."+op.Input)
			bodyArg = "body"
		}
		args = append(args, "options?: RequestOptions")
		if op.Stream {
			fmt.Fprintf(&b, "  /** %s %s: server-sent events, read with for await; break or options.signal closes it. */\n", op.Method, op.Path)
			fmt.Fprintf(&b, "  %s(%s): AsyncGenerator<%s, void, undefined> {\n", op.ID, strings.Join(args, ", "), ret)
			fmt.Fprintf(&b, "    return stream<%s>(%q, %s, %s, options)\n  },\n", ret, op.Method, tsPath(op.Path), bodyArg)
			continue
		}
		fmt.Fprintf(&b, "  /** %s %s */\n", op.Method, op.Path)
		fmt.Fprintf(&b, "  %s(%s): Promise<%s> {\n", op.ID, strings.Join(args, ", "), ret)
		fmt.Fprintf(&b, "    return request<%s>(%q, %s, %s, options)\n  },\n", ret, op.Method, tsPath(op.Path), bodyArg)
	}
	b.WriteString("}\n")
	return b.String()
}

// tsHelpers build a request and read an error reply, for request and
// stream.
const tsHelpers = `/** The path with its query string, and the fetch options. */
function prepare(method: string, path: string, body: unknown, accept: string, options?: RequestOptions): [string, RequestInit] {
  const headers: Record<string, string> = { Accept: accept, ...defaultHeaders, ...options?.headers }
  const init: RequestInit = { method, headers, signal: options?.signal }
  if (options?.body !== undefined) {
    // A raw body: the cookie session accepts it same-origin.
    init.body = options.body
    const own = typeof Blob !== 'undefined' && options.body instanceof Blob ? options.body.type : ''
    const type = options.contentType ?? own
    if (type) headers['Content-Type'] = type
    else if (!(typeof FormData !== 'undefined' && options.body instanceof FormData)) headers['Content-Type'] = 'application/octet-stream'
  } else {
    // Every request that can change state is declared JSON, body or not:
    // a cookie session is only accepted with this content type (CSRF guard).
    if (method !== 'GET' && method !== 'HEAD') headers['Content-Type'] = 'application/json'
    if (body !== undefined) init.body = JSON.stringify(body)
  }
  if (options?.query) {
    const q = new URLSearchParams()
    for (const [k, v] of Object.entries(options.query)) if (v !== undefined && v !== null) q.set(k, String(v))
    const s = q.toString()
    if (s) path += (path.includes('?') ? '&' : '?') + s
  }
  return [path, init]
}

function parse(text: string): unknown {
  if (!text) return undefined
  try {
    return JSON.parse(text)
  } catch {
    return text
  }
}

function failure(method: string, path: string, status: number, statusText: string, parsed: unknown): ApiError {
  const message = (parsed as Partial<T.ApiErrorBody> | undefined)?.error ?? statusText
  return new ApiError(status, parsed, ` + "`${method} ${path}: ${status} ${message}`" + `)
}

`

// tsRequest sends a request and reads its JSON reply.
const tsRequest = `async function request<R>(method: string, path: string, body: unknown, options?: RequestOptions): Promise<R> {
  const [url, init] = prepare(method, path, body, 'application/json', options)
  const res = await fetch(baseUrl + url, init)
  const parsed = parse(await res.text())
  if (!res.ok) throw failure(method, url, res.status, res.statusText, parsed)
  return parsed as R
}

`

// tsStream reads a router.Stream reply: server-sent events whose data is
// one JSON value each, closed by an "end" event; an "error" event
// carries the error body with its status.
const tsStream = `/** Reads a server-sent event stream, one JSON value per event. Leaving
 * the loop or aborting options.signal closes the connection. */
async function* stream<E>(method: string, path: string, body: unknown, options?: RequestOptions): AsyncGenerator<E, void, undefined> {
  const [url, init] = prepare(method, path, body, 'text/event-stream', options)
  const res = await fetch(baseUrl + url, init)
  if (!res.ok || !res.body) throw failure(method, url, res.status, res.statusText, parse(await res.text()))
  const reader = res.body.pipeThrough(new TextDecoderStream()).getReader()
  let buffer = ''
  try {
    for (;;) {
      const { done, value } = await reader.read()
      if (done) break
      buffer += value.replace(/\r/g, '')
      let end: number
      while ((end = buffer.indexOf('\n\n')) >= 0) {
        const block = buffer.slice(0, end)
        buffer = buffer.slice(end + 2)
        let event = 'message'
        const data: string[] = []
        for (const line of block.split('\n')) {
          if (line.startsWith('event:')) event = line.slice(6).trim()
          else if (line.startsWith('data:')) data.push(line.slice(line.startsWith('data: ') ? 6 : 5))
        }
        if (data.length === 0) continue
        const parsed = parse(data.join('\n'))
        if (event === 'end') return
        if (event === 'error') throw failure(method, url, (parsed as { status?: number } | undefined)?.status ?? 500, 'error', parsed)
        yield parsed as E
      }
    }
  } finally {
    await reader.cancel().catch(() => undefined)
  }
  throw new ApiError(res.status, undefined, ` + "`${method} ${url}: the stream closed before its end`" + `)
}

`

// tsUpload sends a router.File route's body: the file, its type as
// Content-Type and its name in Content-Disposition. fetch cannot report
// upload progress, so onProgress takes XMLHttpRequest.
const tsUpload = `/** Uploads file as the raw body and reads the JSON reply. */
async function upload<R>(method: string, path: string, file: Blob, options?: UploadOptions): Promise<R> {
  const { onProgress, ...rest } = options ?? {}
  const [url, init] = prepare(method, path, undefined, 'application/json', { ...rest, body: file })
  const headers = init.headers as Record<string, string>
  const name = (file as { name?: unknown }).name
  if (typeof name === 'string' && name) {
    const encoded = encodeURIComponent(name).replace(/['()*!]/g, (c) => '%' + c.charCodeAt(0).toString(16).toUpperCase())
    headers['Content-Disposition'] = "attachment; filename*=UTF-8''" + encoded
  }
  if (!onProgress) {
    const res = await fetch(baseUrl + url, init)
    const parsed = parse(await res.text())
    if (!res.ok) throw failure(method, url, res.status, res.statusText, parsed)
    return parsed as R
  }
  return new Promise<R>((resolve, reject) => {
    const xhr = new XMLHttpRequest()
    xhr.open(method, baseUrl + url)
    for (const [k, v] of Object.entries(headers)) xhr.setRequestHeader(k, v)
    xhr.upload.onprogress = (e) => onProgress(e.loaded, e.lengthComputable ? e.total : file.size)
    xhr.onload = () => {
      const parsed = parse(xhr.responseText)
      if (xhr.status >= 200 && xhr.status < 300) resolve(parsed as R)
      else reject(failure(method, url, xhr.status, xhr.statusText, parsed))
    }
    xhr.onerror = () => reject(new ApiError(0, undefined, ` + "`${method} ${url}: network error`" + `))
    xhr.onabort = () => reject(new DOMException('The upload was aborted', 'AbortError'))
    const signal = options?.signal
    if (signal?.aborted) return reject(new DOMException('The upload was aborted', 'AbortError'))
    signal?.addEventListener('abort', () => xhr.abort(), { once: true })
    xhr.send(file)
  })
}

`

// tsPath renders "/api/v1/posts/{id}" as a template literal with encoded
// parameters.
func tsPath(path string) string {
	out := "`" + path + "`"
	for _, name := range pathParamsOf(path) {
		out = strings.ReplaceAll(out, "{"+name+"}", "${p(params."+name+")}")
		out = strings.ReplaceAll(out, "{"+name+"...}", "${params."+name+"}")
	}
	return strings.ReplaceAll(out, "{$}", "")
}

// usesEncodedParam reports whether a path has a {name} parameter, the
// kind the client encodes with p (a {name...} one is sent as is).
func usesEncodedParam(ops []inspect.Operation) bool {
	for _, op := range ops {
		for _, name := range pathParamsOf(op.Path) {
			if strings.Contains(op.Path, "{"+name+"}") {
				return true
			}
		}
	}
	return false
}

func pathParamsOf(path string) []string {
	var out []string
	for _, seg := range strings.Split(path, "/") {
		if strings.HasPrefix(seg, "{") && strings.HasSuffix(seg, "}") && seg != "{$}" {
			out = append(out, strings.TrimSuffix(strings.Trim(seg, "{}"), "..."))
		}
	}
	return out
}
