// Package sdk generates the client SDKs from a project's operations. The
// TypeScript client, imported as @lidza/client, is written to
// .lidza/client and regenerated whenever the Go types change.
package sdk

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/agim/lidza/pkg/inspect"
)

// ClientDir is where the TypeScript client lives, relative to the project
// root. The template aliases @lidza/client to ClientDir/index.ts.
const ClientDir = ".lidza/client"

// TypeScript renders the client as files keyed by name: types.ts (the
// component schemas as interfaces and unions), client.ts (one function
// per operation) and index.ts.
func TypeScript(c *inspect.Context) map[string]string {
	return map[string]string{
		"types.ts":      tsTypes(c),
		"client.ts":     tsClient(c),
		"validators.ts": tsValidators(c),
		"index.ts":      "// Code generated by lidza. DO NOT EDIT.\n\nexport * from './types'\nexport * from './client'\nexport * from './validators'\n",
	}
}

// WriteTypeScript writes the client into root/.lidza/client, touching only
// files whose content changed so Vite does not reload needlessly.
func WriteTypeScript(root string, c *inspect.Context) error {
	dir := filepath.Join(root, ClientDir)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	for name, content := range TypeScript(c) {
		p := filepath.Join(dir, name)
		if old, err := os.ReadFile(p); err == nil && string(old) == content {
			continue
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func tsTypes(c *inspect.Context) string {
	var b strings.Builder
	b.WriteString("// Code generated by lidza from the Go handler types. DO NOT EDIT.\n\n")
	b.WriteString("export interface ApiErrorBody {\n  error: string\n}\n\n")
	b.WriteString("export interface ValidationErrorBody {\n  error: 'validation'\n  fields: { field: string; rule: string; message: string }[]\n}\n\n")
	names := make([]string, 0, len(c.Schemas))
	for name := range c.Schemas {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		def, _ := c.Schemas[name].(map[string]any)
		if enum, ok := def["enum"].([]any); ok {
			vals := make([]string, len(enum))
			for i, v := range enum {
				vals[i] = fmt.Sprintf("%q", v)
			}
			fmt.Fprintf(&b, "export type %s = %s\n", name, strings.Join(vals, " | "))
			fmt.Fprintf(&b, "export const %sValues: readonly %s[] = [%s]\n\n", name, name, strings.Join(vals, ", "))
			continue
		}
		if enum, ok := def["enum"].([]string); ok {
			vals := make([]string, len(enum))
			for i, v := range enum {
				vals[i] = fmt.Sprintf("%q", v)
			}
			fmt.Fprintf(&b, "export type %s = %s\n", name, strings.Join(vals, " | "))
			fmt.Fprintf(&b, "export const %sValues: readonly %s[] = [%s]\n\n", name, name, strings.Join(vals, ", "))
			continue
		}
		if def["type"] == "object" && def["properties"] != nil {
			fmt.Fprintf(&b, "export interface %s %s\n\n", name, objectBody(def, 0))
			continue
		}
		fmt.Fprintf(&b, "export type %s = %s\n\n", name, tsType(def, 0))
	}
	return b.String()
}

// objectBody renders "{ a: T; b?: U }" across lines.
func objectBody(def map[string]any, depth int) string {
	props, _ := def["properties"].(map[string]any)
	required := map[string]bool{}
	switch req := def["required"].(type) {
	case []string:
		for _, r := range req {
			required[r] = true
		}
	case []any:
		for _, r := range req {
			required[fmt.Sprint(r)] = true
		}
	}
	names := make([]string, 0, len(props))
	for n := range props {
		names = append(names, n)
	}
	sort.Strings(names)
	pad := strings.Repeat("  ", depth+1)
	var b strings.Builder
	b.WriteString("{\n")
	for _, n := range names {
		opt := ""
		if !required[n] {
			opt = "?"
		}
		fmt.Fprintf(&b, "%s%s%s: %s\n", pad, tsKey(n), opt, tsType(props[n].(map[string]any), depth+1))
	}
	b.WriteString(strings.Repeat("  ", depth) + "}")
	return b.String()
}

func tsKey(name string) string {
	for i, r := range name {
		ok := r == '_' || r == '$' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (i > 0 && r >= '0' && r <= '9')
		if !ok {
			return fmt.Sprintf("%q", name)
		}
	}
	return name
}

// tsType renders a JSON Schema as a TypeScript type expression.
func tsType(def map[string]any, depth int) string {
	if len(def) == 0 {
		return "unknown"
	}
	if r, ok := def["$ref"].(string); ok {
		return strings.TrimPrefix(r, "#/components/schemas/")
	}
	if one, ok := def["oneOf"].([]any); ok {
		parts := make([]string, len(one))
		for i, o := range one {
			parts[i] = tsType(o.(map[string]any), depth)
		}
		return strings.Join(parts, " | ")
	}
	if enum, ok := def["enum"]; ok {
		var parts []string
		switch e := enum.(type) {
		case []any:
			for _, v := range e {
				parts = append(parts, fmt.Sprintf("%q", v))
			}
		case []string:
			for _, v := range e {
				parts = append(parts, fmt.Sprintf("%q", v))
			}
		}
		return strings.Join(parts, " | ")
	}
	if c, ok := def["const"]; ok {
		return fmt.Sprintf("%q", c)
	}
	nullable := false
	var typ string
	switch t := def["type"].(type) {
	case string:
		typ = t
	case []any:
		for _, x := range t {
			if x == "null" {
				nullable = true
			} else {
				typ = fmt.Sprint(x)
			}
		}
	}
	var out string
	switch typ {
	case "string":
		out = "string"
	case "integer", "number":
		out = "number"
	case "boolean":
		out = "boolean"
	case "null":
		return "null"
	case "array":
		items, _ := def["items"].(map[string]any)
		inner := tsType(items, depth)
		if strings.Contains(inner, " | ") {
			inner = "(" + inner + ")"
		}
		out = inner + "[]"
	case "object":
		if def["properties"] != nil {
			out = objectBody(def, depth)
		} else if ap, ok := def["additionalProperties"].(map[string]any); ok {
			out = "Record<string, " + tsType(ap, depth) + ">"
		} else {
			out = "Record<string, unknown>"
		}
	default:
		out = "unknown"
	}
	if nullable {
		out += " | null"
	}
	return out
}

func tsClient(c *inspect.Context) string {
	var b strings.Builder
	b.WriteString("// Code generated by lidza from the Go handlers. DO NOT EDIT.\n\n")
	b.WriteString("import type * as T from './types'\n\n")
	b.WriteString(`export class ApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly body: unknown,
    message: string,
  ) {
    super(message)
    this.name = 'ApiError'
  }

  /** The field errors when the server replied 422. */
  get fields(): T.ValidationErrorBody['fields'] | undefined {
    const body = this.body as Partial<T.ValidationErrorBody> | undefined
    return body?.error === 'validation' ? body.fields : undefined
  }
}

export interface RequestOptions {
  signal?: AbortSignal
  headers?: Record<string, string>
}

let baseUrl = ''
let defaultHeaders: Record<string, string> = {}

/** Set a base URL when the API is not on the page's origin, and headers
 * sent with every request (the server renderer forwards the visitor's). */
export function configure(options: { baseUrl?: string; headers?: Record<string, string> }): void {
  if (options.baseUrl !== undefined) baseUrl = options.baseUrl.replace(/\/$/, '')
  if (options.headers !== undefined) defaultHeaders = { ...options.headers }
}

async function request<R>(method: string, path: string, body: unknown, options?: RequestOptions): Promise<R> {
  const headers: Record<string, string> = { Accept: 'application/json', ...defaultHeaders, ...options?.headers }
  const init: RequestInit = { method, headers, signal: options?.signal }
  // Every request that can change state is declared JSON, body or not: a
  // cookie session is only accepted with this content type (CSRF guard).
  if (method !== 'GET' && method !== 'HEAD') headers['Content-Type'] = 'application/json'
  if (body !== undefined) init.body = JSON.stringify(body)
  const res = await fetch(baseUrl + path, init)
  const text = await res.text()
  let parsed: unknown = undefined
  if (text) {
    try {
      parsed = JSON.parse(text)
    } catch {
      parsed = text
    }
  }
  if (!res.ok) {
    const message = (parsed as Partial<T.ApiErrorBody> | undefined)?.error ?? res.statusText
    throw new ApiError(res.status, parsed, ` + "`${method} ${path}: ${res.status} ${message}`" + `)
  }
  return parsed as R
}

const p = encodeURIComponent

`)
	b.WriteString("export const api = {\n")
	for _, op := range c.Operations {
		var args []string
		if len(op.Params) > 0 {
			fields := make([]string, len(op.Params))
			for i, name := range op.Params {
				fields[i] = tsKey(name) + ": string"
			}
			args = append(args, "params: { "+strings.Join(fields, "; ")+" }")
		}
		bodyArg := "undefined"
		if op.Input != "" {
			args = append(args, "body: T."+op.Input)
			bodyArg = "body"
		}
		args = append(args, "options?: RequestOptions")
		ret := "void"
		if op.Output != "" {
			ret = "T." + op.Output
		}
		fmt.Fprintf(&b, "  /** %s %s */\n", op.Method, op.Path)
		fmt.Fprintf(&b, "  %s(%s): Promise<%s> {\n", op.ID, strings.Join(args, ", "), ret)
		fmt.Fprintf(&b, "    return request<%s>(%q, %s, %s, options)\n  },\n", ret, op.Method, tsPath(op.Path), bodyArg)
	}
	b.WriteString("}\n")
	return b.String()
}

// tsPath renders "/api/v1/posts/{id}" as a template literal with encoded
// parameters.
func tsPath(path string) string {
	out := "`" + path + "`"
	for _, name := range pathParamsOf(path) {
		out = strings.ReplaceAll(out, "{"+name+"}", "${p(params."+name+")}")
		out = strings.ReplaceAll(out, "{"+name+"...}", "${params."+name+"}")
	}
	return strings.ReplaceAll(out, "{$}", "")
}

func pathParamsOf(path string) []string {
	var out []string
	for _, seg := range strings.Split(path, "/") {
		if strings.HasPrefix(seg, "{") && strings.HasSuffix(seg, "}") && seg != "{$}" {
			out = append(out, strings.TrimSuffix(strings.Trim(seg, "{}"), "..."))
		}
	}
	return out
}
