package sdk

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/agim/lidza/pkg/inspect"
)

// tsValidators renders validators.ts: one function per object type that
// carries rules from schema.lidza (minLength, pattern, enum, ...), applying
// the same checks as the generated Go Validate, so a form can reject bad
// input before the request and show the field errors the server would.
func tsValidators(c *inspect.Context) string {
	var b strings.Builder
	b.WriteString("// Code generated by lidza from the schema rules. DO NOT EDIT.\n\n")

	names := make([]string, 0, len(c.Schemas))
	for name := range c.Schemas {
		names = append(names, name)
	}
	sort.Strings(names)
	var generated []string
	var funcs strings.Builder
	for _, name := range names {
		def, _ := c.Schemas[name].(map[string]any)
		props, _ := def["properties"].(map[string]any)
		if def["type"] != "object" || len(props) == 0 || def["x-lidza"] != "schema" {
			continue
		}
		body := validatorBody(def, c.Schemas)
		if body == "" {
			continue
		}
		generated = append(generated, name)
		fmt.Fprintf(&funcs, "export function validate%s(v: T.%s): FieldError[] {\n  const errs: FieldError[] = []\n%s  return errs\n}\n\n", name, name, body)
	}
	// The import and the helpers only when a validator uses them: the
	// template compiles with noUnusedLocals.
	if len(generated) > 0 {
		b.WriteString("import type * as T from './types'\n\n")
	}
	b.WriteString("export interface FieldError {\n  field: string\n  rule: string\n  message: string\n}\n\n")
	if strings.Contains(funcs.String(), "EMAIL.test(") {
		b.WriteString("const EMAIL = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/\n\n")
	}
	if strings.Contains(funcs.String(), "isURL(") {
		b.WriteString("function isURL(s: string): boolean {\n  try {\n    const u = new URL(s)\n    return (u.protocol === 'http:' || u.protocol === 'https:') && u.host !== ''\n  } catch {\n    return false\n  }\n}\n\n")
	}
	if strings.Contains(funcs.String(), "DECIMAL.test(") || strings.Contains(funcs.String(), "decimalFits(") {
		b.WriteString(tsDecimalRe)
	}
	if strings.Contains(funcs.String(), "decimalCmp(") {
		b.WriteString(tsDecimalCmp)
	}
	if strings.Contains(funcs.String(), "decimalFits(") {
		b.WriteString(tsDecimalFits)
	}
	b.WriteString(funcs.String())
	b.WriteString("export const validators = {\n")
	for _, name := range generated {
		fmt.Fprintf(&b, "  %s: validate%s,\n", name, name)
	}
	b.WriteString("}\n")
	return b.String()
}

// validatorBody renders the checks of one type; "" when it has no rules.
func validatorBody(def map[string]any, all map[string]any) string {
	props, _ := def["properties"].(map[string]any)
	required := map[string]bool{}
	switch req := def["required"].(type) {
	case []string:
		for _, r := range req {
			required[r] = true
		}
	case []any:
		for _, r := range req {
			required[fmt.Sprint(r)] = true
		}
	}
	fields := make([]string, 0, len(props))
	for f := range props {
		fields = append(fields, f)
	}
	sort.Strings(fields)
	var b strings.Builder
	for _, field := range fields {
		p, _ := props[field].(map[string]any)
		acc := "v." + tsKey(field)
		nullable := false
		typ := ""
		switch t := p["type"].(type) {
		case string:
			typ = t
		case []any:
			for _, x := range t {
				if x == "null" {
					nullable = true
				} else {
					typ = fmt.Sprint(x)
				}
			}
		}
		if _, ok := p["oneOf"]; ok {
			nullable = true
		}
		var rules []string
		add := func(cond, rule, msg string) {
			rules = append(rules, fmt.Sprintf("if (%s) errs.push({ field: %q, rule: %q, message: %q })", cond, field, rule, msg))
		}
		enumValues := enumOf(p, all)
		switch {
		case len(enumValues) > 0:
			quoted := make([]string, len(enumValues))
			for i, v := range enumValues {
				quoted[i] = fmt.Sprintf("%q", v)
			}
			if required[field] && !nullable {
				add(fmt.Sprintf("(%s as string) === ''", acc), "required", "required")
			}
			add(fmt.Sprintf("(%s as string) !== '' && ![%s].includes(%s as string)", acc, strings.Join(quoted, ", "), acc), "enum", "unknown value")
		case typ == "string" && p["format"] == "decimal":
			// Exact: digits compared as BigInt, never through a float.
			if prec, ok := num(p["x-precision"]); ok {
				scale, _ := num(p["x-scale"])
				msg := "not a number with at most " + minus(prec, scale) + " digit(s) before the point and " + scale + " after"
				if scale == "0" {
					msg = "not a whole number of at most " + prec + " digit(s)"
				}
				add(fmt.Sprintf("!decimalFits(%s, %s, %s)", acc, prec, scale), "decimal", msg)
			} else {
				add(fmt.Sprintf("!DECIMAL.test(%s)", acc), "decimal", "not a decimal number")
			}
			if n, ok := p["x-minimum"].(string); ok {
				add(fmt.Sprintf("DECIMAL.test(%s) && decimalCmp(%s, %q) < 0", acc, acc, n), "min", "at least "+n)
			}
			if n, ok := p["x-maximum"].(string); ok {
				add(fmt.Sprintf("DECIMAL.test(%s) && decimalCmp(%s, %q) > 0", acc, acc, n), "max", "at most "+n)
			}
		case typ == "string":
			if required[field] && !nullable && p["format"] != "uuid" {
				add(acc+" === ''", "required", "required")
			}
			if n, ok := num(p["minLength"]); ok {
				add(fmt.Sprintf("%s.length < %s", acc, n), "min", "at least "+n+" character(s)")
			}
			if n, ok := num(p["maxLength"]); ok {
				add(fmt.Sprintf("%s.length > %s", acc, n), "max", "at most "+n+" character(s)")
			}
			if p["format"] == "email" {
				add(fmt.Sprintf("%s !== '' && !EMAIL.test(%s)", acc, acc), "email", "not an email address")
			}
			if p["format"] == "uri" {
				add(fmt.Sprintf("%s !== '' && !isURL(%s)", acc, acc), "url", "not an http(s) URL")
			}
			if pat, ok := p["pattern"].(string); ok {
				add(fmt.Sprintf("%s !== '' && !new RegExp(%q).test(%s)", acc, "^(?:"+pat+")$", acc), "pattern", "does not match "+pat)
			}
		case typ == "integer" || typ == "number":
			if n, ok := num(p["minimum"]); ok {
				add(fmt.Sprintf("%s < %s", acc, n), "min", "at least "+n)
			}
			if n, ok := num(p["maximum"]); ok {
				add(fmt.Sprintf("%s > %s", acc, n), "max", "at most "+n)
			}
		case typ == "array":
			if n, ok := num(p["minItems"]); ok {
				add(fmt.Sprintf("%s.length < %s", acc, n), "min", "at least "+n+" item(s)")
			}
			if n, ok := num(p["maxItems"]); ok {
				add(fmt.Sprintf("%s.length > %s", acc, n), "max", "at most "+n+" item(s)")
			}
		}
		if len(rules) == 0 {
			continue
		}
		if nullable {
			fmt.Fprintf(&b, "  if (%s !== null && %s !== undefined) {\n", acc, acc)
			for _, r := range rules {
				b.WriteString("    " + r + "\n")
			}
			b.WriteString("  }\n")
			continue
		}
		for _, r := range rules {
			b.WriteString("  " + r + "\n")
		}
	}
	return b.String()
}

// enumOf resolves a property's enum values, following a $ref or a oneOf
// with null to an enum component.
func enumOf(p map[string]any, all map[string]any) []string {
	target := p
	if ref, ok := p["$ref"].(string); ok {
		target, _ = all[strings.TrimPrefix(ref, "#/components/schemas/")].(map[string]any)
	} else if one, ok := p["oneOf"].([]any); ok {
		for _, o := range one {
			if m, ok := o.(map[string]any); ok {
				if ref, ok := m["$ref"].(string); ok {
					target, _ = all[strings.TrimPrefix(ref, "#/components/schemas/")].(map[string]any)
				}
			}
		}
	}
	if target == nil {
		return nil
	}
	switch e := target["enum"].(type) {
	case []string:
		return e
	case []any:
		out := make([]string, len(e))
		for i, v := range e {
			out[i] = fmt.Sprint(v)
		}
		return out
	}
	return nil
}

// The decimal helpers of validators.ts: a decimal is a string, compared
// digit for digit as BigInt at a common scale.
const tsDecimalRe = "const DECIMAL = /^[+-]?[0-9]+(\\.[0-9]+)?$/\n\n"

const tsDecimalCmp = `function decimalScaled(s: string, scale: number): bigint {
  const neg = s.startsWith('-')
  const [whole, frac = ''] = s.replace(/^[+-]/, '').split('.')
  const v = BigInt(whole + frac.padEnd(scale, '0'))
  return neg ? -v : v
}

function decimalCmp(a: string, b: string): number {
  const scale = Math.max((a.split('.')[1] ?? '').length, (b.split('.')[1] ?? '').length)
  const x = decimalScaled(a, scale)
  const y = decimalScaled(b, scale)
  return x < y ? -1 : x > y ? 1 : 0
}

`

const tsDecimalFits = `function decimalFits(s: string, precision: number, scale: number): boolean {
  if (!DECIMAL.test(s)) return false
  const [whole, frac = ''] = s.replace(/^[+-]/, '').split('.')
  return frac.replace(/0+$/, '').length <= scale && whole.replace(/^0+/, '').length <= precision - scale
}

`

// minus renders a - b for two whole numbers printed by num.
func minus(a, b string) string {
	x, _ := strconv.Atoi(a)
	y, _ := strconv.Atoi(b)
	return strconv.Itoa(x - y)
}

func num(v any) (string, bool) {
	switch n := v.(type) {
	case float64:
		s := strings.TrimRight(strings.TrimRight(fmt.Sprintf("%.6f", n), "0"), ".")
		return s, true
	case int:
		return fmt.Sprint(n), true
	case int64:
		return fmt.Sprint(n), true
	}
	return "", false
}
