// Code generated by lidza gen from pack.lidza.json. DO NOT EDIT.

package stats

import (
	"context"
	_ "embed"
	"time"

	"github.com/agim/lidza"
	"github.com/agim/lidza/pkg/engine"

	"notes/schema"
)

//go:embed stats.wasm
var wasm []byte

// Stats is the stats pack: Word statistics for a note: counts, reading time, top words. Rust, because it is one CPU pass over user text with no I/O.
type Stats struct {
	module *engine.Module
	pool   *engine.Pool
}

// Pack returns the pack for packs.go.
func Pack() lidza.Pack { return &Stats{} }

// From returns the running pack from a request context.
func From(ctx context.Context) *Stats { return lidza.Service[*Stats](ctx) }

// Name implements lidza.Pack.
func (p *Stats) Name() string { return "stats" }

// Start compiles the module, warms the instance pool and registers the
// pack as a service.
func (p *Stats) Start(ctx context.Context, s *lidza.Services) error {
	m, err := engine.Compile(ctx, wasm, engine.Options{MemoryMB: 64, Uninterruptible: true})
	if err != nil {
		return err
	}
	pool, err := engine.NewPool(ctx, m, 4, 2000*time.Millisecond)
	if err != nil {
		m.Close(ctx)
		return err
	}
	p.module, p.pool = m, pool
	lidza.Provide(s, p)
	return nil
}

// Stop releases the instances and the module.
func (p *Stats) Stop(ctx context.Context) error {
	if p.pool != nil {
		_ = p.pool.Close(ctx)
	}
	if p.module != nil {
		return p.module.Close(ctx)
	}
	return nil
}

// TelemetryStats reports the pool to /metrics.
func (p *Stats) TelemetryStats() map[string]float64 { return p.pool.Stats() }

// TextStats: Word count, unique words, reading minutes at 200 words a minute, and the most frequent words of a text.
// Rules: text up to 100000 characters; top (default 5, at most 50) caps topWords.
func (p *Stats) TextStats(ctx context.Context, in schema.TextStatsInput) (schema.TextStats, error) {
	var out schema.TextStats
	err := engine.CallJSON(ctx, p.pool, "text_stats", in, &out)
	return out, err
}
