// Code generated by lidza gen from schema.lidza. DO NOT EDIT.

#![allow(dead_code)]

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AuthSession {
    pub id: String,
    pub subject: String,
    #[serde(rename = "refreshHash")]
    pub refresh_hash: String,
    #[serde(rename = "prevRefreshHash")]
    pub prev_refresh_hash: Option<String>,
    #[serde(rename = "rotatedAt")]
    pub rotated_at: Option<String>,
    #[serde(rename = "expiresAt")]
    pub expires_at: String,
    #[serde(rename = "revokedAt")]
    pub revoked_at: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct User {
    pub id: String,
    pub email: String,
    #[serde(rename = "passwordHash")]
    pub password_hash: String,
    #[serde(rename = "verifiedAt")]
    pub verified_at: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Note {
    pub id: String,
    #[serde(rename = "ownerId")]
    pub owner_id: String,
    pub title: String,
    pub body: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AuthToken {
    pub id: String,
    pub purpose: String,
    pub subject: String,
    pub hash: String,
    #[serde(rename = "expiresAt")]
    pub expires_at: String,
    #[serde(rename = "usedAt")]
    pub used_at: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MailMessage {
    pub id: String,
    pub recipient: String,
    pub subject: String,
    pub text: Option<String>,
    pub html: Option<String>,
    pub template: Option<String>,
    pub status: String,
    #[serde(rename = "providerId")]
    pub provider_id: Option<String>,
    pub error: Option<String>,
    pub attempts: i32,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "sentAt")]
    pub sent_at: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LLMUsage {
    pub id: String,
    pub at: String,
    pub provider: String,
    pub model: String,
    pub label: String,
    pub input: i32,
    pub output: i32,
    pub ms: i32,
    pub status: String,
    pub error: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CreateNote {
    pub title: String,
    pub body: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct UpdateNote {
    pub title: Option<String>,
    pub body: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NoteList {
    pub items: Vec<Note>,
    pub total: i32,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Credentials {
    pub email: String,
    pub password: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Session {
    #[serde(rename = "userId")]
    pub user_id: String,
    pub email: String,
    pub verified: bool,
    #[serde(rename = "accessToken")]
    pub access_token: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct VerifyEmail {
    pub token: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ForgotPassword {
    pub email: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ResetPassword {
    pub token: String,
    pub password: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SessionState {
    pub user: Option<Session>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TextStatsInput {
    pub text: String,
    pub top: Option<i32>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TextStats {
    pub words: i32,
    pub unique: i32,
    #[serde(rename = "readingMinutes")]
    pub reading_minutes: f64,
    #[serde(rename = "topWords")]
    pub top_words: Vec<WordCount>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NoteTags {
    pub tags: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct WordCount {
    pub word: String,
    pub count: i32,
}

