// Code generated by lidza gen from schema.lidza. DO NOT EDIT.

package schema

import (
	"github.com/agim/lidza/pkg/validate"
	"time"
)

// AuthSession is a row of the auth_session table.
type AuthSession struct {
	ID              string     `json:"id" db:"id"`
	Subject         string     `json:"subject" db:"subject"`
	RefreshHash     string     `json:"refreshHash" db:"refresh_hash"`
	PrevRefreshHash *string    `json:"prevRefreshHash" db:"prev_refresh_hash"`
	RotatedAt       *time.Time `json:"rotatedAt" db:"rotated_at"`
	ExpiresAt       time.Time  `json:"expiresAt" db:"expires_at"`
	RevokedAt       *time.Time `json:"revokedAt" db:"revoked_at"`
	CreatedAt       time.Time  `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of AuthSession from schema.lidza.
func (v AuthSession) Validate() error {
	var errs validate.Errors
	if v.Subject == "" {
		errs.Add("subject", "required", "required")
	}
	if v.RefreshHash == "" {
		errs.Add("refreshHash", "required", "required")
	}
	return errs.Result()
}

// User is a row of the app_user table.
type User struct {
	ID           string     `json:"id" db:"id"`
	Email        string     `json:"email" db:"email"`
	PasswordHash string     `json:"passwordHash" db:"password_hash"`
	VerifiedAt   *time.Time `json:"verifiedAt" db:"verified_at"`
	CreatedAt    time.Time  `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of User from schema.lidza.
func (v User) Validate() error {
	var errs validate.Errors
	if v.Email == "" {
		errs.Add("email", "required", "required")
	}
	if len(v.Email) < 3 {
		errs.Add("email", "min", "at least 3 character(s)")
	}
	if len(v.Email) > 200 {
		errs.Add("email", "max", "at most 200 character(s)")
	}
	if v.PasswordHash == "" {
		errs.Add("passwordHash", "required", "required")
	}
	return errs.Result()
}

// Note is a row of the note table.
type Note struct {
	ID        string    `json:"id" db:"id"`
	OwnerID   string    `json:"ownerId" db:"owner_id"`
	Title     string    `json:"title" db:"title"`
	Body      *string   `json:"body" db:"body"`
	CreatedAt time.Time `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of Note from schema.lidza.
func (v Note) Validate() error {
	var errs validate.Errors
	if v.OwnerID == "" {
		errs.Add("ownerId", "required", "required")
	}
	if v.Title == "" {
		errs.Add("title", "required", "required")
	}
	if len(v.Title) < 1 {
		errs.Add("title", "min", "at least 1 character(s)")
	}
	if len(v.Title) > 200 {
		errs.Add("title", "max", "at most 200 character(s)")
	}
	return errs.Result()
}

// AuthToken is a row of the auth_token table.
type AuthToken struct {
	ID        string     `json:"id" db:"id"`
	Purpose   string     `json:"purpose" db:"purpose"`
	Subject   string     `json:"subject" db:"subject"`
	Hash      string     `json:"hash" db:"hash"`
	ExpiresAt time.Time  `json:"expiresAt" db:"expires_at"`
	UsedAt    *time.Time `json:"usedAt" db:"used_at"`
	CreatedAt time.Time  `json:"createdAt" db:"created_at"`
}

// Validate applies the rules of AuthToken from schema.lidza.
func (v AuthToken) Validate() error {
	var errs validate.Errors
	if v.Purpose == "" {
		errs.Add("purpose", "required", "required")
	}
	if v.Subject == "" {
		errs.Add("subject", "required", "required")
	}
	if v.Hash == "" {
		errs.Add("hash", "required", "required")
	}
	return errs.Result()
}

// MailMessage is a row of the mail_message table.
type MailMessage struct {
	ID         string     `json:"id" db:"id"`
	Recipient  string     `json:"recipient" db:"recipient"`
	Subject    string     `json:"subject" db:"subject"`
	Text       *string    `json:"text" db:"text"`
	HTML       *string    `json:"html" db:"html"`
	Template   *string    `json:"template" db:"template"`
	Status     string     `json:"status" db:"status"`
	ProviderID *string    `json:"providerId" db:"provider_id"`
	Error      *string    `json:"error" db:"error"`
	Attempts   int        `json:"attempts" db:"attempts"`
	CreatedAt  time.Time  `json:"createdAt" db:"created_at"`
	SentAt     *time.Time `json:"sentAt" db:"sent_at"`
}

// Validate applies the rules of MailMessage from schema.lidza.
func (v MailMessage) Validate() error {
	var errs validate.Errors
	if v.Recipient == "" {
		errs.Add("recipient", "required", "required")
	}
	if v.Subject == "" {
		errs.Add("subject", "required", "required")
	}
	if v.Status == "" {
		errs.Add("status", "required", "required")
	}
	return errs.Result()
}

// CreateNote is an API type.
type CreateNote struct {
	Title string  `json:"title"`
	Body  *string `json:"body"`
}

// Validate applies the rules of CreateNote from schema.lidza.
func (v CreateNote) Validate() error {
	var errs validate.Errors
	if v.Title == "" {
		errs.Add("title", "required", "required")
	}
	if len(v.Title) < 1 {
		errs.Add("title", "min", "at least 1 character(s)")
	}
	if len(v.Title) > 200 {
		errs.Add("title", "max", "at most 200 character(s)")
	}
	return errs.Result()
}

// UpdateNote is an API type.
type UpdateNote struct {
	Title *string `json:"title"`
	Body  *string `json:"body"`
}

// Validate applies the rules of UpdateNote from schema.lidza.
func (v UpdateNote) Validate() error {
	var errs validate.Errors
	if v.Title != nil {
		x := *v.Title
		if len(x) < 1 {
			errs.Add("title", "min", "at least 1 character(s)")
		}
		if len(x) > 200 {
			errs.Add("title", "max", "at most 200 character(s)")
		}
	}
	return errs.Result()
}

// NoteList is an API type.
type NoteList struct {
	Items []Note `json:"items"`
	Total int    `json:"total"`
}

// Validate applies the rules of NoteList from schema.lidza.
func (v NoteList) Validate() error {
	var errs validate.Errors
	for _, x := range v.Items {
		if err := x.Validate(); err != nil {
			errs.Add("items", "nested", err.Error())
			break
		}
	}
	return errs.Result()
}

// Credentials is an API type.
type Credentials struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Validate applies the rules of Credentials from schema.lidza.
func (v Credentials) Validate() error {
	var errs validate.Errors
	if v.Email == "" {
		errs.Add("email", "required", "required")
	}
	if len(v.Email) > 200 {
		errs.Add("email", "max", "at most 200 character(s)")
	}
	if v.Email != "" && !validate.Email(v.Email) {
		errs.Add("email", "email", "not an email address")
	}
	if v.Password == "" {
		errs.Add("password", "required", "required")
	}
	if len(v.Password) < 8 {
		errs.Add("password", "min", "at least 8 character(s)")
	}
	if len(v.Password) > 200 {
		errs.Add("password", "max", "at most 200 character(s)")
	}
	return errs.Result()
}

// Session is an API type.
type Session struct {
	UserID      string `json:"userId"`
	Email       string `json:"email"`
	Verified    bool   `json:"verified"`
	AccessToken string `json:"accessToken"`
}

// Validate applies the rules of Session from schema.lidza.
func (v Session) Validate() error {
	var errs validate.Errors
	if v.UserID == "" {
		errs.Add("userId", "required", "required")
	}
	if v.Email == "" {
		errs.Add("email", "required", "required")
	}
	if v.AccessToken == "" {
		errs.Add("accessToken", "required", "required")
	}
	return errs.Result()
}

// VerifyEmail is an API type.
type VerifyEmail struct {
	Token string `json:"token"`
}

// Validate applies the rules of VerifyEmail from schema.lidza.
func (v VerifyEmail) Validate() error {
	var errs validate.Errors
	if v.Token == "" {
		errs.Add("token", "required", "required")
	}
	if len(v.Token) < 1 {
		errs.Add("token", "min", "at least 1 character(s)")
	}
	return errs.Result()
}

// ForgotPassword is an API type.
type ForgotPassword struct {
	Email string `json:"email"`
}

// Validate applies the rules of ForgotPassword from schema.lidza.
func (v ForgotPassword) Validate() error {
	var errs validate.Errors
	if v.Email == "" {
		errs.Add("email", "required", "required")
	}
	if len(v.Email) > 200 {
		errs.Add("email", "max", "at most 200 character(s)")
	}
	if v.Email != "" && !validate.Email(v.Email) {
		errs.Add("email", "email", "not an email address")
	}
	return errs.Result()
}

// ResetPassword is an API type.
type ResetPassword struct {
	Token    string `json:"token"`
	Password string `json:"password"`
}

// Validate applies the rules of ResetPassword from schema.lidza.
func (v ResetPassword) Validate() error {
	var errs validate.Errors
	if v.Token == "" {
		errs.Add("token", "required", "required")
	}
	if len(v.Token) < 1 {
		errs.Add("token", "min", "at least 1 character(s)")
	}
	if v.Password == "" {
		errs.Add("password", "required", "required")
	}
	if len(v.Password) < 8 {
		errs.Add("password", "min", "at least 8 character(s)")
	}
	if len(v.Password) > 200 {
		errs.Add("password", "max", "at most 200 character(s)")
	}
	return errs.Result()
}

// SessionState is an API type.
type SessionState struct {
	User *Session `json:"user"`
}

// Validate applies the rules of SessionState from schema.lidza.
func (v SessionState) Validate() error {
	var errs validate.Errors
	if v.User != nil {
		x := *v.User
		if err := x.Validate(); err != nil {
			errs.Add("user", "nested", err.Error())
		}
	}
	return errs.Result()
}

// TextStatsInput is an API type.
type TextStatsInput struct {
	Text string `json:"text"`
	Top  *int   `json:"top"`
}

// Validate applies the rules of TextStatsInput from schema.lidza.
func (v TextStatsInput) Validate() error {
	var errs validate.Errors
	if v.Text == "" {
		errs.Add("text", "required", "required")
	}
	if len(v.Text) > 100000 {
		errs.Add("text", "max", "at most 100000 character(s)")
	}
	return errs.Result()
}

// TextStats is an API type.
type TextStats struct {
	Words          int         `json:"words"`
	Unique         int         `json:"unique"`
	ReadingMinutes float64     `json:"readingMinutes"`
	TopWords       []WordCount `json:"topWords"`
}

// Validate applies the rules of TextStats from schema.lidza.
func (v TextStats) Validate() error {
	var errs validate.Errors
	for _, x := range v.TopWords {
		if err := x.Validate(); err != nil {
			errs.Add("topWords", "nested", err.Error())
			break
		}
	}
	return errs.Result()
}

// WordCount is an API type.
type WordCount struct {
	Word  string `json:"word"`
	Count int    `json:"count"`
}

// Validate applies the rules of WordCount from schema.lidza.
func (v WordCount) Validate() error {
	var errs validate.Errors
	if v.Word == "" {
		errs.Add("word", "required", "required")
	}
	return errs.Result()
}
