package pack

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/agim/lidza/pkg/schema"
)

// PacksFile is the generated registry in the app's main package.
const PacksFile = "packs.go"

// GeneratePackGo renders packs/<name>/pack.go: the pack type, its
// lifecycle (compile, pool, register) and one typed method per capability.
func GeneratePackGo(m *Manifest, module string) string {
	var b strings.Builder
	typ := exported(m.Name)
	b.WriteString("// Code generated by lidza gen from " + ManifestFile + ". DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", m.Name)
	b.WriteString("import (\n\t\"context\"\n\t_ \"embed\"\n\t\"time\"\n\n\t\"github.com/agim/lidza\"\n\t\"github.com/agim/lidza/pkg/engine\"\n")
	if len(m.Capabilities) > 0 {
		fmt.Fprintf(&b, "\n\t\"%s/schema\"\n", module)
	}
	b.WriteString(")\n\n")
	fmt.Fprintf(&b, "//go:embed %s.wasm\nvar wasm []byte\n\n", m.Name)
	fmt.Fprintf(&b, "// %s is the %s pack: %s\ntype %s struct {\n\tmodule *engine.Module\n\tpool   *engine.Pool\n}\n\n", typ, m.Name, m.Description, typ)
	fmt.Fprintf(&b, "// Pack returns the pack for packs.go.\nfunc Pack() lidza.Pack { return &%s{} }\n\n", typ)
	fmt.Fprintf(&b, "// From returns the running pack from a request context.\nfunc From(ctx context.Context) *%s { return lidza.Service[*%s](ctx) }\n\n", typ, typ)
	fmt.Fprintf(&b, "// Name implements lidza.Pack.\nfunc (p *%s) Name() string { return %q }\n\n", typ, m.Name)
	fmt.Fprintf(&b, `// Start compiles the module, warms the instance pool and registers the
// pack as a service.
func (p *%s) Start(ctx context.Context, s *lidza.Services) error {
	m, err := engine.Compile(ctx, wasm, engine.Options{MemoryMB: %d})
	if err != nil {
		return err
	}
	pool, err := engine.NewPool(ctx, m, %d, %d*time.Millisecond)
	if err != nil {
		m.Close(ctx)
		return err
	}
	p.module, p.pool = m, pool
	lidza.Provide(s, p)
	return nil
}

// Stop releases the instances and the module.
func (p *%s) Stop(ctx context.Context) error {
	if p.pool != nil {
		_ = p.pool.Close(ctx)
	}
	if p.module != nil {
		return p.module.Close(ctx)
	}
	return nil
}

`, typ, m.Rust.MemoryMB, m.Rust.Instances, m.Rust.TimeoutMS, typ)
	for _, c := range m.Capabilities {
		fmt.Fprintf(&b, "// %s: %s\n", exported(c.Name), c.Description)
		if c.Rules != "" {
			fmt.Fprintf(&b, "// Rules: %s\n", c.Rules)
		}
		fmt.Fprintf(&b, "func (p *%s) %s(ctx context.Context, in schema.%s) (schema.%s, error) {\n\tvar out schema.%s\n\terr := engine.CallJSON(ctx, p.pool, %q, in, &out)\n\treturn out, err\n}\n\n",
			typ, exported(c.Name), c.Input, c.Output, c.Output, c.Name)
	}
	return b.String()
}

// GeneratePacksGo renders the app's packs.go from the enabled pack names.
func GeneratePacksGo(module string, names []string) string {
	var b strings.Builder
	b.WriteString("// Code generated by lidza gen from lidza.json. DO NOT EDIT.\n\npackage main\n\n")
	if len(names) == 0 {
		b.WriteString("import \"github.com/agim/lidza\"\n\n// packs lists the packs lidza.json enables; none yet. `lidza pack scaffold <name>` adds one.\nfunc packs() []lidza.Pack { return nil }\n")
		return b.String()
	}
	b.WriteString("import (\n\t\"github.com/agim/lidza\"\n\n")
	for _, n := range names {
		fmt.Fprintf(&b, "\t%s \"%s/%s/%s\"\n", n, module, Dir, n)
	}
	b.WriteString(")\n\n// packs lists the packs lidza.json enables, started in this order.\nfunc packs() []lidza.Pack {\n\treturn []lidza.Pack{\n")
	for _, n := range names {
		fmt.Fprintf(&b, "\t\t%s.Pack(),\n", n)
	}
	b.WriteString("\t}\n}\n")
	return b.String()
}

// Generate writes packs.go and, for every enabled pack, pack.go and the
// crate's schema.rs (the app schema as serde types). It returns the files
// it changed, relative to root.
func Generate(root, module string, names []string, s *schema.Schema) ([]string, error) {
	var changed []string
	write := func(rel, content string) error {
		p := filepath.Join(root, rel)
		if old, err := os.ReadFile(p); err == nil && string(old) == content {
			return nil
		}
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			return err
		}
		changed = append(changed, filepath.ToSlash(rel))
		return os.WriteFile(p, []byte(content), 0o644)
	}
	if err := write(PacksFile, GeneratePacksGo(module, names)); err != nil {
		return nil, err
	}
	for _, name := range names {
		m, err := Load(root, name)
		if err != nil {
			return nil, err
		}
		if err := write(m.GoFile(), GeneratePackGo(m, module)); err != nil {
			return nil, err
		}
		if s != nil {
			if err := write(filepath.Join(m.CrateDir(), schema.RustFile), schema.GenerateRust(s)); err != nil {
				return nil, err
			}
		}
	}
	return changed, nil
}

var initialisms = map[string]bool{"id": true, "url": true, "api": true, "http": true, "json": true, "uuid": true, "sql": true, "ip": true, "html": true, "db": true}

// exported turns snake_case into an exported identifier: image_resize ->
// ImageResize, db -> DB.
func exported(s string) string {
	var b strings.Builder
	for _, part := range strings.Split(s, "_") {
		if part == "" {
			continue
		}
		if initialisms[part] {
			b.WriteString(strings.ToUpper(part))
		} else {
			b.WriteString(strings.ToUpper(part[:1]) + part[1:])
		}
	}
	return b.String()
}
