-- Code generated by lidza gen from schema.lidza. DO NOT EDIT.
-- The current schema in full; migrations in db/migrations carry the changes.

CREATE TABLE auth_session (
  id text PRIMARY KEY,
  subject text NOT NULL,
  refresh_hash text NOT NULL UNIQUE,
  prev_refresh_hash text,
  rotated_at timestamptz,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX auth_session_subject_idx ON auth_session (subject);

CREATE TABLE app_user (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email varchar(200) NOT NULL UNIQUE,
  password_hash text NOT NULL,
  verified_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE note (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL,
  title varchar(200) NOT NULL,
  body text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX note_owner_id_idx ON note (owner_id);

CREATE TABLE auth_token (
  id text PRIMARY KEY,
  purpose text NOT NULL,
  subject text NOT NULL,
  hash text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX auth_token_purpose_idx ON auth_token (purpose);
CREATE INDEX auth_token_subject_idx ON auth_token (subject);

CREATE TABLE mail_message (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  recipient text NOT NULL,
  subject text NOT NULL,
  text text,
  html text,
  template text,
  status text NOT NULL,
  provider_id text,
  error text,
  attempts integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  sent_at timestamptz
);
CREATE INDEX mail_message_recipient_idx ON mail_message (recipient);
CREATE INDEX mail_message_status_idx ON mail_message (status);
CREATE INDEX mail_message_created_at_idx ON mail_message (created_at);

CREATE TABLE llm_usage (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  at timestamptz NOT NULL DEFAULT now(),
  provider text NOT NULL,
  model text NOT NULL,
  label text NOT NULL,
  input integer NOT NULL,
  output integer NOT NULL,
  ms integer NOT NULL,
  status text NOT NULL,
  error text
);
CREATE INDEX llm_usage_at_idx ON llm_usage (at);
CREATE INDEX llm_usage_label_idx ON llm_usage (label);

CREATE TABLE auth_account (
  subject text PRIMARY KEY,
  label text,
  disabled_at timestamptz,
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE auth_user (
  subject text PRIMARY KEY,
  email text UNIQUE,
  name text,
  password_hash text,
  verified_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE auth_identity (
  id text PRIMARY KEY,
  provider text NOT NULL,
  provider_subject text NOT NULL,
  subject text NOT NULL,
  email text,
  name text,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_used_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX auth_identity_provider_idx ON auth_identity (provider);
CREATE INDEX auth_identity_subject_idx ON auth_identity (subject);

