-- Queries for Note, generated by lidza gen resource and scoped to the
-- owner by hand: every query takes the signed-in user's id.

-- name: ListNotes :many
SELECT * FROM note WHERE owner_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3;

-- name: CountNotes :one
SELECT count(*) FROM note WHERE owner_id = $1;

-- name: GetNote :one
SELECT * FROM note WHERE id = $1 AND owner_id = $2;

-- name: CreateNote :one
INSERT INTO note (owner_id, title, body) VALUES ($1, $2, $3) RETURNING *;

-- name: UpdateNote :one
UPDATE note SET title = COALESCE(sqlc.narg('title'), title), body = COALESCE(sqlc.narg('body'), body)
WHERE id = sqlc.arg('id') AND owner_id = sqlc.arg('owner_id') RETURNING *;

-- name: DeleteNote :execrows
DELETE FROM note WHERE id = $1 AND owner_id = $2;
